### ISSUE TITLE
Wrong MLT values.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#105]
As reported in https://github.com/ESA-VirES/MagneticModel/issues/3, the values of the Magnetic Local Time are not correct.

**Comment by pacesm** [comment]
The bug is fixed by https://github.com/ESA-VirES/VirES-Server/commit/e5dccf6fa730733755c2f1766883c3ed90507659
The testing > staging > production deployment is still to be done.

**Comment by santilland** [comment]
* Testing to staging done (907d5b33885d06b0c8c76ea80b0f513fedc14f9c)
* Staging to production done (8fbd1e5271a4882addc1f0f55b285142c391f360)
Bug fix introduced to production, if agreed ticket will be closed.

**Comment by pacesm** [comment]
Seems to be all right. I am closing this ticket.
