### ISSUE TITLE
z-index of window

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#106]
When wanting to download a product from a browser with small viewport, as the timeslider has the same z-index (1004) as the timeslider, the download window ends up being behind the time slider. Could it be possible to adjust the z-indices so the window is on top, as using the timeslider when in the download window is of minimal use?

**Comment by miktoki** [comment]
Same goes for drop-down menu of x-axis parameter. 

![screenshot from 2016-05-23 15 50 31](https://cloud.githubusercontent.com/assets/17086561/15472998/2229adbe-20fe-11e6-853a-79d182395cff.png)

**Comment by lubojr** [comment]
z-index of the download panel has been increased to go over timeslider panel, deployed on staging

**Comment by lmar76** [comment]
Tested.
