### ISSUE TITLE
Parameter dropdown menu

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#107]
In the y-axis parameter dropdown menu there are two buttons at the bottom, "OK" and "Cancel". Currently "Cancel" does not seem to serve any purpose other than closing the window (which will happen anyway if you click anywhere outside the menu).

I suggest removing the "Cancel"-button and renaming "OK" to "Apply".

**Comment by miktoki** [comment]
If "Cancel" should be kept, it should uncheck the parameters which are not yet visualized.

**Comment by santilland** [comment]
Cancel unchecks paramters not yet visualized, closing the issue for now. If there is more need for discussion please feel free to comment.
