### ISSUE TITLE
Custom data download- add context-specific fields? [suggestion]

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#109]
It has been proposed to add a "custom fields" checkbox to customise the downloaded product. A list with what parameters to add to the download should then appear. 

There are some context-specific values (eg residuals between magnetic field model and swarm magnetic measurements) which might have a natural place among these parameters. 

Could these values be added to the final product, and if yes, how complex would you expect the implementation to be?

**Comment by miktoki** [comment]
Other context specific parameters: satellite (when selecting data from multiple satellites), boolean values for if value is highlighted (assuming highlighting does not filter away data from the product)

**Comment by santilland** [comment]
With introduction of custom parameters in download this has been introduced. Feel free to comment.
