### ISSUE TITLE
Y axis values of Radius plot

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#117]
In the scatter plot of the Radius parameter, the values on the Y axis do not match the Radius values visualized when clicking on each sample. E.g. in the image below, the radius value for the selected sample is 6832073.41 (meters) while the corresponding value on Y axis (see grid line for reference) is 832000 (meters?). Observing the value it seems that the radius has been converted to an "altitude" but 832 km seems a bit too high. Anyway, an altitude value could be misleading because the user is expecting to see a radius. What do you think about?
 
![capture](https://cloud.githubusercontent.com/assets/20207042/18465178/b20823a8-7995-11e6-9387-bd85ef16b37b.PNG)

**Comment by pacesm** [comment]
It seems the leading 6 has been clipped out.
6832000 -> 832000

**Comment by santilland** [comment]
Thanks, it seems the formatting is not ideal (it is not easy to get good formatting for such a wide range of values) or at least the margin to show the full number, will look into it.

**Comment by santilland** [comment]
Made sure there is enough margin to not clip values for radius, as the range (stepsize) of values for radius can be quite small (but with large numbers) i think this is the best solution. It is deployed in staging and can be tested. I will close the ticket now, if there is any comment or issue please let me know and we can reopen the ticket.
