### ISSUE TITLE
B_n_error, B_e_error, B_c_error parameters

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#119]
In the analytics view there is the possibility to plot the B_n_error, B_e_error, B_c_error parameters which should be the components of the B_error vector.

According to the Swarm Level 1b Product Definition (SW-RS-DSC-SY-0007), the B_error is the error estimate on magnetic field vector in the VFM frame (i.e. not the NEC frame) and it is related to the B_VFM parameter (i.e. not the B_NEC). Naming the 3 components: B_n_error, B_e_error, B_c_error could be misleading because a user could think that their reference frame is NEC. What do you think about?

**Comment by santilland** [comment]
Yes, i also think this to be confusing and should be renamed (if kept, see below). 
The question is then if we should include B_VFM parameters additional to the B_NEC parameters, i guess having the error values for something that can't be visualized does not make much sense. So we should either include B_VFM and rename the error components, or remove the error components.
What is the interest for the B_VFM component for scientists?

**Comment by pacesm** [comment]
Just for reference, see also [MAGX_LR_1B_Product definition](http://swarm-wiki.spacecenter.dk/mediawiki-1.21.1/index.php/Level_1b_Product_Definitions#MAGX_LR_1B_Product).

**Comment by santilland** [comment]
So seeing VFM stands for Vector Field Magnetometer, how should we name each of the components?
B_1_error, B_2_error, B_3_error?
B_0_error, B_1_error, B_2_error?
If we take in B_VFM we should use the same component naming for all VFM vector data.
Any other ideas?

**Comment by pacesm** [comment]
I do not think using the number for the axis without further description is not the best idea. If the VFM frame is aligned with the space-craft principal axes then the labels should be derived from these [[see Aircraft Principal Axes](https://en.wikipedia.org/wiki/Aircraft_principal_axes)]

**Comment by lmar76** [comment]
I talked to two guys working in the data quality team. It seems that the B_VFM components are simply called X, Y, and Z. To further specify that we are talking about B_VFM we could use the names below. What do you think about?


![preview](https://cloud.githubusercontent.com/assets/20207042/18547029/96ad227c-7b41-11e6-998e-f511ea9046d2.png)

**Comment by santilland** [comment]
I like the idea, will work on it.

**Comment by pacesm** [comment]
OK, should not we actually describe all vector variables consistently (including B_NEC) using the X,Y,Z axes subscripts?

**Comment by miktoki** [comment]
FYI: in the community X=B_N, Y=B_E, Z=B_C (In addition sometimes B_r, B_phi and B_theta/B_lambda are used, which are coordinate transformations of the ones above). 

Using B_x, B_y and B_z would not be normal when referring to the NEC reference system, but makes sense when using it on the VFM reference frame. 

Luca's suggestion works, but I would not do the same for B_NEC.

Either way, the errors in the VFM should be representative of the errors in NEC frame (due to the orbit and attitude of the satellites and how the errors typically are scaled by a common factor for all vector components)

**Comment by santilland** [comment]
In the new update (staging) B_VFM was added and the components for B_VFM and B_error have now   X,Y,Z appended, i will close this ticket to have an overview of what is done, if there is any other point to consider feel free to comment, we can reopen the issue at any time if necessary.
