### ISSUE TITLE
Inverted Timestamp Y axis on v1.1

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#120]
On version v1.1 (currently on staging server) the Timestamp Y axis appears "inverted" (i.e. the time increases from top to bottom) if compared to the same plot on the previous v1.0 (see screenshots below). Is there a particular reason for this change?

Moreover, there is a fixed unit "ms" for the Timestamp parameters which does not fit the time values. These values depend on te zoom level and time selection and can be years, months, days, hours, etc. Thus, in my opinion, or the unit is dynamically updated, or it is better to remove it leaving only "Timestamp".

v1.0
![v1_0](https://cloud.githubusercontent.com/assets/20207042/18632111/0c905ac2-7e76-11e6-971b-69878093a342.PNG)

v1.1
![v1_1](https://cloud.githubusercontent.com/assets/20207042/18632117/15c866b6-7e76-11e6-84db-d030c558a925.PNG)

**Comment by santilland** [comment]
There is no reason for the change in direction, it was probably introduced during the integration of the second y-Axis and will be reverted.
For the unit of measurement the information of the actual products is taken, but it does not make too much sense to display it for the time value as it is converted to a human readable format, not any more maintaining the original format when visualizing. 
Therefore i would poropose to not show a unit for the time value.

**Comment by lmar76** [comment]
I agree with you.

**Comment by santilland** [comment]
The time axis for y was reverted to the same direction as before and the unit of measurement removed, as discussed. I will close the issue, if there is any other feedback please comment.
