### ISSUE TITLE
Magnetic field vector visualization on globe not visible - major

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#121]
Issue observed on v1.1 (staging).

After selecting the "Magnetic field vector, NEC frame" visualization in the MAGx_LR_1B layer properties, the layer plot on the globe is not updated (i.e. it is still visualized the magnetic field intensity). The magnetic field vectors on the globe are visible only if the visualization changes (e.g. selecting an additional layer or changing the view type).

![capture1](https://cloud.githubusercontent.com/assets/20207042/18705311/109a142c-7fee-11e6-8b97-70ebe0602489.PNG)

**Comment by santilland** [comment]
Issue solved during introduction of new data organization which needed some rework of how to handle different parameters from different products in the rendering of cesium. Working now tested with various combinations of datasets and vector and scalar data mixed. 
Closing the issue now, if any other issues related to this are found please comment here.
