### ISSUE TITLE
Error visualizing fieldlines - major

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#122]
Issue observed on v1.1 (staging)

Selecting a model in the layers list and changing the visualized parameter to "Fieldlines" in the layer's settings, an HTTP error message appears (see image).

![capture](https://cloud.githubusercontent.com/assets/20207042/18705525/e4580044-7fee-11e6-8c5c-de96c4c01a41.PNG)

**Comment by santilland** [comment]
Issue introduced with automatic calculation of ranges, which does not apply to fieldlines. Therefore i actually removed the coefficient range attributes from the settings panel as they have no effect in the algorithm to calculate the field lines. Added check for special fieldline case, so there is no longer an error message. 
I am closing the issue now, if there is still any comment or something not working as expected please comment.
