### ISSUE TITLE
Overlapping labels in the globe map

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#124]
Issue observed on v1.1 (staging)

Trying to visualize different parameters for a given model, i.e. changing the parameter in the layer's settings, the label shown in the globe map overlaps the one of the previous parameter. E.g. consider the total field intensity for the SIFM model: the labels are correctly visualized under the globe:

![capture](https://cloud.githubusercontent.com/assets/20207042/18706262/912c738e-7ff1-11e6-992b-7f59a7777b91.PNG)

changing the parameter to "horizontal intensity" and then to "east component" the labels are overlapped:

![capture2](https://cloud.githubusercontent.com/assets/20207042/18706334/dfaa58dc-7ff1-11e6-9617-9662b491906f.PNG)

![capture3](https://cloud.githubusercontent.com/assets/20207042/18706345/e63bbeb6-7ff1-11e6-8d9f-f442458b7344.PNG)

**Comment by santilland** [comment]
Was not clearing the canvas where i render the texture to correctly, leaving the previous attribute, solved in current release (staging). Closing the ticket, if any other issue appears related to this please comment here and we can reopen the issue.
