### ISSUE TITLE
Deselection of default MAGA_LR_1B

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#125]
Issue observed on v1.1 (staging).

Deselecting the (default) MAGA_LR_1B layer the plot of the F parameter remains visible in the analytic view:

![staging](https://cloud.githubusercontent.com/assets/20207042/18706468/6d7226f4-7ff2-11e6-9c82-270e7edd8756.PNG)

This behaviour is different from the one observed on the operational vires where the F plot disappear if the default MAGA_LR_1B layer is deselected.

![op](https://cloud.githubusercontent.com/assets/20207042/18706496/8a7af870-7ff2-11e6-87ad-e3ce4862bf4b.PNG)

**Comment by lmar76** [comment]
I think it is a good idea.

**Comment by santilland** [comment]
This has been introduced to the current deployment in staging. Closing the issue, if something not as expected please comment.
