### ISSUE TITLE
Kp and Dst plots on time bar

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#126]
Issue observed on v1.1 (staging).

The colors of the Kp and Dst plots on the time bar have changed from v1.0. Now they are quite similar and can be confused (see screenshots below).

![staging](https://cloud.githubusercontent.com/assets/20207042/18713477/bca590c4-8012-11e6-8d14-46a576d5aa11.PNG)

![op](https://cloud.githubusercontent.com/assets/20207042/18713461/b46dae14-8012-11e6-8249-7c2de146a3e1.PNG)

**Comment by santilland** [comment]
Colors have been changed back to previous ones, closing the issue, if there is any other comment please do.
