### ISSUE TITLE
Kp and Dst plots visible up to end of April 2016 on staging

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#127]
Issue observed on v1.1 (staging).

The Kp and Dst plots (both in the time bar and in the analytic view) are visible up to end of April 2016.

**Comment by santilland** [comment]
Staging is not thought to be operational and not all synchronization routines run there, it uses another server and databases then the operations deployment. So just the data is older here, i don't think this to be an issue and if the explanation clarifies things and you agree i would close this.

**Comment by lmar76** [comment]
Ok Daniel, I agree. Thanks.
