### ISSUE TITLE
Double Y axis for the initial (default) F plot

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#129]
Issue observed on v1.1 (staging).

In the "initial" F plot shown by VirES, two equal Y axes are visualized.

![image](https://cloud.githubusercontent.com/assets/20207042/18781539/81fa5b28-8182-11e6-8bca-ca9b88b1b076.png)

Selecting another parameter and deselecting the F only one Y axis is shown (the usual one on the left). Changing back to the F plot (selecting only F) only one Y axis is present.

![image](https://cloud.githubusercontent.com/assets/20207042/18781565/9c8dd9a6-8182-11e6-8942-e5702c969a82.png)

**Comment by santilland** [comment]
Issue introduced with the automatic additional selection of the parameter when adding a new product type, added check to make sure selection is added only if it is not already selected which solves the issue (currently deployed in staging).
Closing the issue, if something is not solved or working as expected please comment.
