### ISSUE TITLE
Internal Error message

### ISSUE THREAD

**Issue by triebnigg** [ESA-VirES/WebClient-Framework#13]
1) 
External login from mobile (Drei network) or laptop (ÖBB train router) leads to "Internal Error" message.

2) 
Minor typo in "Internal Error" message
"Please contact the server administrator at support@vires.services to inform them ..."
pls. change to plural:
""Please contact the server administrators  ..."

**Comment by pacesm** [comment]
This is not a SW bug but rather misconfiguration of the deployment web server.
