### ISSUE TITLE
Kp parameter missing

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#131]
Issue observed on v1.1 (staging).

The Kp parameter is missing from the lists of parameter in the analytics view and it is not possible to plot it.

**Comment by santilland** [comment]
Kp parameter was removed incorrectly. It was added again but for now not added automatically to the filters section as when activating other products there is little space for all parameters. I propose to keep it this way, but the default activated filter parameters can be changed any time. Please let me know what you think.

**Comment by lmar76** [comment]
I think it's ok.
