### ISSUE TITLE
Labels for parameters with subscripts not correctly visualized

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#135]
The labels appearing while pointing with the mouse over the parameter's list, in the case of parameters with subscripts (e.g. B_C or F_error) are not correctly visualized. E.g.:

![image](https://cloud.githubusercontent.com/assets/20207042/18837937/ecbd4b3e-8405-11e6-9c07-f8eacf0e25fb.png)

![image](https://cloud.githubusercontent.com/assets/20207042/18837968/01e5b5c8-8406-11e6-83a2-fefecd99c5e8.png)

**Comment by santilland** [comment]
Unluckily the tooltip does not allow the use of subscript tags, so as a solution for now i replace the sub tags with underscore getting the original names, i.e. B_C or F_error is shown as tooltip.
If this is acceptable solution i would close this issue.

**Comment by lmar76** [comment]
For me it is acceptable.
