### ISSUE TITLE
Timestamp parameter in CSV export not in human readable format

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#136]
The Timestamp parameter in the CSV export is not in human readable format as it was in the previous version. E.g.: 1456876800 instead of "yyyy-mm-dd hh:mm:ss".

**Comment by santilland** [comment]
This was changed now (current staging) back to human readable format is used in CSV output. For CDF format still CDF_EPOCH is used as in original product. 
Closing the issue, if it is considered something should be done differently or behaviour not as expected, please comment here.
