### ISSUE TITLE
Additional parameters in the default data download

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#137]
Trying to download magnetic data (both in CDF and CSV format) for a given day, the parameters: Kp, Dst, QDLat, QDLon, MLT are present but they are not part of the original MAGx_LR_1B data. The default download (i.e. not the custom one) should be similar to the original Swarm product as much as possible.

**Comment by santilland** [comment]
Ok, so i for now (locally) i changed it to only have parameters as defined in the product if no custom selection has been done.
Right now the strange thing i observed checking the MAG LR cdf files for comparison is there seems to be a "SyncStatus" parameter inside the CDF i do not find anywhere defined in the documents. There is a SyncStatus for the EFI data defined but as far as i can tell, not for MAG LR, what should be do with this?

**Comment by lmar76** [comment]
According to the Swarm L1b Product Definition:

[Swarm L1b Product Definition](https://earth.esa.int/web/guest/document-library/browse-document-library/-/article/swarm-level-1b-product-definition)

the SyncStatus parameter is define also for MAG-LR (see section 6.2 at page 50).

**Comment by santilland** [comment]
Ok, perfect thanks, i think the SyncStatus is missing at least in some definitions, i will add it in any case

**Comment by santilland** [comment]
In the currently deployed version (staging) this behaviour was introduced, meaning when not selecting custom download "only" the parameters available in the data are used. Other parameters such as MLT or QDLat can be added as custom parameter.
I consider this as solved and will close the ticket, if there is any other discussion point or something not working as expected please comment here.
