### ISSUE TITLE
Satellite id in the downloaded data

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#138]
In the downloaded CSV data (both for single and multiple satellites) the satellite id (e.g. Alpha, Bravo, Charlie) is present.

In the downloaded CDF data (both for single and multiple satellites) the satellite id is **not** present. If the user tries to download data related to more the one satellite, it cannot distinguish if a record belongs to one satellite or another.

I propose to align the content of CDF and CSV formats. Maybe it is better to add the satellite id only if the user tries to download data for multiple satellites just to keep the downloaded data as similar as possible to the original Swarm data. Please let me know what do you think.

**Comment by santilland** [comment]
I think this i a good approach but would mean right now changes in the process so i would pospone these changes for a bit later

**Comment by santilland** [comment]
The id has now been added to the CDF when the user downloads multiproduct data.
Closing the ticket, feel free to add any other related comments.
