### ISSUE TITLE
IBI default parameter in the analytics view

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#140]
After the application startup, the default parameter (F) for layer MAG LR (S/C A) is plotted in the analytics view.

Selecting layer for Plasma data (S/C A) the additional default parameter (n) is plotted in addition to the previous one.

Selecting layer for IBI data (S/C A) the additional default parameter (Bubble_probability) is **not** added to the analytics view.

Deselecting all the layers and adding again the IBI one, the default parameter (Bubble_probability) is plotted.

**Comment by santilland** [comment]
This was a bit of a design decision, as IBI data (Bubbles) not so abundant and the probability has a range between 0 and 1 activating it automatically for the scatter plot felt a bit strange as it is normally always 0. I considered it more useful to add the probability parameter as filter.
In any case this can of course be changed, just wanted to describe my idea behind the change. 
What do you think?

**Comment by lmar76** [comment]
Ok Daniel, I agree. Please, leave as it is.
