### ISSUE TITLE
Default selected time range

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#141]
The current default selected time range at startup (on staging) is 10:00-11:00 of 02/03/2016. Due to this setting the user often needs to change the selection to the desired time period (in some cases different months or years). It could be very useful if the application could "save" the last selected time period (at least the start date) and present it to the user once the application is started again (or the page refreshed).

**Comment by santilland** [comment]
I think this is a good idea, what we could do is save the information on the local "storage" of the browser and when the user uses the same browser it will load on the last selected time. This should be fairly straight forward.
If we actually want synchronization based on user id on server, we would need to adapt the database, extend the user model and create an interface that allows for a user to change parameters on the server. Then a user could log in on another computer and get the same time selection.
I would recommend the first version as the work/use relation is definitely much better. Having a synchronized user across every user device does not seem like the typical use case to me. What do you think?

I guess the same question will arise if we want to "save" the workspace status (so there is some relevance to think about it now) it will be a lot easier to do it locally for a browser, maybe we could even allow exporting the status as some kind of json object so it can be sent to a friend.

**Comment by lmar76** [comment]
I think that the first solution is good enough. One thing that should be assessed is the case when the user, in the previous session, selected a "long" time interval. Maybe in this case there could be a delay during the first access (due to the plot of a big amount of data).

**Comment by lmar76** [comment]
I think my initial request has been implemented with the "resume session" functionality introduced with v1.2.
