### ISSUE TITLE
Plasma bubbles representation on time bar

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#144]
Comparing the plasma bubbles representation on the time bar with the Kp and Dst representations, it appears that all the plasma bubbles points are at the same "height" and there is no Y axis. E.g.:

![image](https://cloud.githubusercontent.com/assets/20207042/18879709/9f555690-84d5-11e6-9c01-a0cbb1df13d5.png)

I don't know exactly which information is plotted but if it is the Bubble_probability, why don't represent the points at a given height depending on the probability and add a Y axis with values from 0 to 1?

**Comment by santilland** [comment]
As most of the time the probability is 0 using a graph it would be a line at 0 most of the time with spikes going up at certain points, we think that a point showing where a bubble happens is visually more pleasing then the graph.
If there is need for further discussion please comment and we can reopen.
