### ISSUE TITLE
Login via social providers - icons not visible with Safari

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#152]
The icons for the log in via social providers are not visible with Safari (see screenshot below)

<img width="1308" alt="vires log in with safari" src="https://cloud.githubusercontent.com/assets/20207042/19355556/0eb3cd2c-916b-11e6-9203-2f730ce6a6e4.png">

**Comment by Schpidi** [comment]
Hi @lmar76, is it possible that you have an ad blocker, javascript blocker, or similar installed? I for example use Adblock Plus and I only see the Google logo, I guess because I actively allowed it.

**Comment by lmar76** [comment]
Hello, we have repeated the test. Now the icons are visible. Thanks

**Comment by santilland** [comment]
Ok, closing the ticket as it was an issue of used plugins and not of the system itself.
