### ISSUE TITLE
Missing samples from EFIx_PL_1B downloaded data

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#154]
The following EFIx_PL_1B data have been downloaded from VirES in CDF format:

Spacecraft A, day 01/03/2016
Spacecraft B, day 13/03/2016
Spacecraft C, day 01/04/2016

The CDF files downloaded from VirES have been compared with the corresponding Swarm product files:

Spacecraft A, day 01/03/2016: ftp://swarm-diss.eo.esa.int/Level1b/Current/EFIx_PL/Sat_A/SW_OPER_EFIA_PL_1B_20160301T000000_20160301T235959_0403.CDF.ZIP
Spacecraft B, day 13/03/2016: ftp://swarm-diss.eo.esa.int/Level1b/Current/EFIx_PL/Sat_B/SW_OPER_EFIB_PL_1B_20160313T000000_20160313T235959_0403.CDF.ZIP
Spacecraft C, day 01/04/2016: ftp://swarm-diss.eo.esa.int/Level1b/Current/EFIx_PL/Sat_C/SW_OPER_EFIC_PL_1B_20160401T000000_20160401T235959_0403.CDF.ZIP

and it has been verified that, for each parameter, the last two samples present in the Swarm product are not present in the CDF files downloaded from VirES. E.g.:

Spacecraft A, day 01/03/2016, "Timestamp":

Number of samples:
- VirES data: 172396
- Swarm data: 172398
  Missing timestamps:
- 2016-03-01 23:59:59.162000
- 2016-03-01 23:59:59.662000

Spacecraft B, day 13/03/2016, "Timestamp":

Number of samples:
- VirES data: 172409
- Swarm data: 172411
  Missing timestamps:
- 2016-03-13 23:59:59.162000
- 2016-03-13 23:59:59.662000

Spacecraft C, day 01/04/2016, "Timestamp":

Number of samples:
- VirES data: 172536
- Swarm data: 172538
  Missing timestamps:
- 2016-04-01 23:59:59, 162000
- 2016-04-01 23:59:59, 662000

The same test has been performed downloading data from VirES in CSV format for the same days/satellites. The content of the CSV files has been compared with the content of the related Swarm products with the same discrepancies.

**Comment by eox-cs1** [comment]
#154 - manually verified synchronized files (ZIPs and extracted CDFs), no discrepancy could be found (with md5sum). I therefore re-registered these 3 datasets. 
Could you please run your tests again to check if the above error still occurs or if its solved.  Thx.
ciao
Christian

**Comment by lmar76** [comment]
I have repeated the test and I have obtained the same results. Then I have executed an additional test downloading satellite-A data with two days of coverage: 01/03/2016-02/03/2016 and comparing it with the Swarm product files:

ftp://swarm-diss.eo.esa.int/Level1b/Current/EFIx_PL/Sat_A/SW_OPER_EFIA_PL_1B_20160301T000000_20160301T235959_0403.CDF.ZIP
ftp://swarm-diss.eo.esa.int/Level1b/Current/EFIx_PL/Sat_A/SW_OPER_EFIA_PL_1B_20160302T000000_20160302T235959_0403.CDF.ZIP

obtaining the following result:

Number of samples:
- VirES data: 344754
- Swarm data: 344756

Missing timestamps:
- 2016-03-02 23:59:59.162000
- 2016-03-02 23:59:59.662000

It seems that the missing timestamps are always the last two.

Could it be possible that, while creating the output file, VirES performs a query up to 23:59:59, i.e. filtering out the last two timestamps (23:59:59.162 and 23:59:59.662)?

Ciao,
Luca

**Comment by eox-cs1** [comment]
OK, we'll investigate the cause of that.

**Comment by santilland** [comment]
Hello Luca,
thanks for checking and finding the problem, thinking about how data is requested it could be that the request is sent "incorrectly" using 23:59:59:000 time. I need to check and if true update the request to make sure .999 is used. I think the data and process are working as expected. I'll see into it as soon as possible.

**Comment by santilland** [comment]
After examination we found out the problem was in the way how the data was requests, it was indeed requested without milliseconds (for start or end time) so the last two measurements were ("correctly"-based on the request) not included. The request creation has been updated and the expected data should be returned now. If you want to recheck i will wait for now for your ok to close the ticket.

**Comment by lmar76** [comment]
I have repeated the test for Swarm A  data (01/03/2016): now both the CDF and CSV downloaded files contain the last two samples previously missing (2016-03-01T23:59:59.162000Z, 2016-03-01T23:59:59.662000Z) but the downloaded files:

SW_OPER_EFIA_PL_1B_20160301T000000_20160302T000000_Filtered.cdf
SW_OPER_EFIA_PL_1B_20160301T000000_20160302T000000_Filtered.csv

have a validity stop date different from the original one (20160301T235959). Could it be possible to truncate the validity stop to the second 59 in order to keep the file name as close as possible to the original Swarm product (SW_OPER_EFIA_PL_1B_20160301T000000_20160301T235959_0403_MDR_EFI_PL.cdf)?

Thanks,
Luca

**Comment by santilland** [comment]
It makes sense to keep the name as similar as possible, i can request the data for 23:59:59:999 and the name will be as in the original file, the only issue is, if there is any measurement in this or other products that have the timestamp 23:59:59:999 then it will not be included, is this an acceptable alternative?

**Comment by lmar76** [comment]
For the time being it is acceptable. I don't know if it will be still acceptable for other types of data. Why don't request data in the time window: _day-start_ 00:00:00 <= t < _day-stop_+1 00:00:00 (i.e. with day-stop+1 00:00:00 excluded from the query) and write _day-stop_ 235959 in the filename?

**Comment by santilland** [comment]
We already requested the data as you described (day-start 00:00:00 <= t < day-stop+1 00:00:00) but this created the name convention not equal to the original swarm products. Now we updated the process and reduce the end time by one second and it creates the filename 235959 as expected. If there are no objections i would close the ticket now.

**Comment by lmar76** [comment]
Ok, close the ticket.
