### ISSUE TITLE
Default scale range for plasma density

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#155]
The default scale range for the plasma density representation on the globe map is currently set to 100000-200000 but, according to the scatter plot, this parameter usually (I have checked only few days) goes from less than 50000 to more than 1600000. Can you please update the current default scale range to a more realistic one?

**Comment by santilland** [comment]
It is true that the range is larger as you have described but (and i am no scientist) looking at the data it seems the most interesting changes are between ~100000 and ~300000, when i change the range up to 1.6 million it basically smooths out all details. Of course information is lost in the visualization for the really high values but the other way around i think we loose information on the lower end values. It does not feel like a trivial choice, but of course changing the range is no problem at all, so if you think we must use the total possible range as default i can change it. Please let me know.

**Comment by lmar76** [comment]
Ok, I agree with you. I didn't realize the impacts on the loss of information. Please leave it as it is. Maybe for these kind of customizations we need more feedbacks from the users.

**Comment by santilland** [comment]
I am going to close this issue but in order to keep track of the possibility to discuss and reconsider the default ranges with scientists i created a new more general ticket (#158).
