### ISSUE TITLE
Dynamic scale range calculation not working with CHAOS-5_static.shc file

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#156]
When visualizing the field intensity on the globe map obtained loading the [CHAOS-5_static.shc](http://www.spacecenter.dk/files/magnetic-models/CHAOS-5/CHAOS-5_static.shc) file, the dynamic scale range calculation does not work: the range is still 15000-55000 and the globe map has a single color (see image).

![image](https://cloud.githubusercontent.com/assets/20207042/19682492/21750ba0-9aae-11e6-8a81-9df083c79dba.png)

**Comment by santilland** [comment]
For performance reasons (as for models we know the range) we do not initially calculate the range. As we can see here this is not the case for uploaded coefficients, which can have any range, thus we can do firstly a range calculation which will be then used for the visualization. It is already implemented and will be tested and deployed soon.

**Comment by santilland** [comment]
The issue should be solved now. I will mark this as closed, if there are any related things or issues please comment here.
