### ISSUE TITLE
Scale range and unit in the layer settings window not updated after parameter's change

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#157]
Changing the parameter in the layer settings, the plot on the globe map, the color scale and the unit are changed but the range values and unit in the layer settings window are not changed. To visualize the updated values and unit, it has to be closed and reopened.

The issue can be observed selecting the EFI data (this is the unique layer having parameters with different units and ranges) and changing the parameter from the default one (Plasma density) to the others (e.g, see screenshot below for the Spacecraft potential).

![image](https://cloud.githubusercontent.com/assets/20207042/19730851/cb8297d2-9b9b-11e6-9747-3eccf642666a.png)

**Comment by santilland** [comment]
The issue should be solved now. I will mark this as closed, if there are any related things or issues please comment here.
