### ISSUE TITLE
Dst index not available

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#162]
Dst index is no more visible (check performed on 07/11/2016 at 15:30 CET): it is available up ti 31/12/2011:

![image](https://cloud.githubusercontent.com/assets/20207042/20061478/442b1af2-a500-11e6-8a92-68512d64db25.png)

**Comment by santilland** [comment]
The retrieved data seems stable and for now i will close the ticket, if issue should reappear at any time we can rethink the strategies for the future.
