### ISSUE TITLE
Redundant data info in "About"

### ISSUE THREAD

**Issue by triebnigg** [ESA-VirES/WebClient-Framework#163]
There is redundant information in About page 1.1 under "The Data" section.
Remove 1st para "The complete sets of magnetic vector and scalar data at 1 Hz rate at exact UTC seconds is provided for the A, B, and C Swarm satellites (Swarm Level 1b Products MAGX_LR_1B)." As the information is provided in 1st bullet of subsequent para.

**Comment by santilland** [comment]
Removed redundant data (currently in staging), closing the ticket.
