### ISSUE TITLE
Issues on resume previous status (staging)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#167]
1. The following time selection has been done on VirES (see figure):

![chrome1](https://cloud.githubusercontent.com/assets/20207042/20566458/732652bc-b195-11e6-9b1e-b00b14ef757d.PNG)

2. The browser has been closed and started again.
3. At the second access to VirES, the previous status was resumed. The time selection is the same but it appears shifted with respect to the original one (see figure):

![chrome2](https://cloud.githubusercontent.com/assets/20207042/20566619/f6607414-b195-11e6-8073-2c279acac3a1.PNG)

The issue has been observed on Chrome, Firefox and Internet Explorer. On Firefox there is an additional issue: after resuming the previous status, the color scale in the globe map is not visible anymore (see figure):

![firefox](https://cloud.githubusercontent.com/assets/20207042/20567016/774c6bb8-b197-11e6-8289-f33b63ed2ae6.PNG)

**Comment by santilland** [comment]
Thank you for the info, it seems like this could be something that was previously an issue where the timeslider library used a "rounding" mechanism to set the displayed time interval (previously useful to get "nicer" borders).
This was updated in the timeslider and should not be the case anymore. Could you make sure to clear your cache and try again?
If the issue persists than we need to investigate further what the problem could be, i tested it on my side and could not reproduce the problem (for now).

**Comment by lmar76** [comment]
I tried again after cleaning the cache but the issue persists (se figures below). It seems that the time bar is shifted to the right. Please note that with Firefox, after resuming the previous status, the color bar is not visible anymore.

![firefox1](https://cloud.githubusercontent.com/assets/20207042/20568595/4dd6856a-b19d-11e6-9dc7-03fcdc7f5508.PNG)

![firefox2](https://cloud.githubusercontent.com/assets/20207042/20568597/4f3a8866-b19d-11e6-84d6-5557f2b00ce2.PNG)

**Comment by santilland** [comment]
Ok, so it seems that the problem arises after drawing an extent and then refreshing. When only moving the slider it gets the values correctly.
We have been reworking the timeslider widget doing multiple improvements and we are close to a release, we had some issues there which i am relatively sure are related to this issue and i think updating to the next release will solve the problem. We have already a branch testing out the new release to make sure everything works. I think we should be able to get this solved before the end of the week. I will keep you posted.

**Comment by santilland** [comment]
Ok, the new version of the timeslider was included into the latest release in staging, this introduces a number of minor fixes that should increase stability of the timeslider.
After my initial tests this solves the issue of not correct saving of shown time range in timesldier. Please have also a look and let me know.

**Comment by lmar76** [comment]
The issue has been fixed. However, repeating the test with Firefox the additional issue of the not visible colormap is still present. I have repeated the test also with IE but it is not possible to load the GUI (see [#176](https://github.com/ESA-VirES/WebClient-Framework/issues/176) ).

![firefox](https://cloud.githubusercontent.com/assets/20207042/21359723/6dd8786e-c6dd-11e6-94b4-22bf5ca214c9.PNG)

**Comment by santilland** [comment]
The underlying issue with the not appearing colorscale on load of firefox is difficult to understand. It seems to only happen when you load the page the first time after opening the firefox browser. Consecutive loading of the site afterwards works as expected. 
Still need to investigate further.

**Comment by lmar76** [comment]
Fix successfully tested also on IE after resolution of [#176](https://github.com/ESA-VirES/WebClient-Framework/issues/176).

**Comment by santilland** [comment]
As in previous comment, issue related and solved, will be closed now.
