### ISSUE TITLE
"Logout" or "Sign Out"?

### ISSUE THREAD

**Issue by triebnigg** [ESA-VirES/WebClient-Framework#17]
Use consistent language - see attached image
![2016-03-31 2](https://cloud.githubusercontent.com/assets/12813866/14169508/8218c156-f728-11e5-9898-aff62236143b.png)

**Comment by triebnigg** [comment]
I opt to use exclusively the following terms:
* **sign up**: user gets new account in VirES or uses account from social network IDP
* **login**: enter service as authenticated user
* **logout**: leave service
* **sign off**: delete user account 

"Sign in" shall not be used. and "registration" is the term describing that new geophysical data e.g. Swarm products are brought to the system (not user data). 

... written after some research e.g. at http://ux.stackexchange.com/questions/11936/when-to-use-join-register-or-sign-up

**Comment by santilland** [comment]
The previously defined terms were introduced in the templates here:
https://github.com/ESA-VirES/VirES-Server/commit/13c9d967b8ad1774f14de411a361f0f35f16782c

**Comment by miktoki** [comment]
I realize this has been closed, but when testing I find that *login* and *logout* are a bit stiff, and suggest to replace them with *log in* and *log out*.  *login* is a noun, but what one wants the user to do is an action, a verb; to "*log in*" (A login is when a user logs in). See eg [this link](http://www.grammarunderground.com/login-vs-log-in-and-other-one-word-or-two-dilemmas.html).
