### ISSUE TITLE
Warning for model's temporal validity

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#172]
Issue observed on v1.1.

If the user selects a time interval outside the temporal validity of the selected model, a warning message appears showing the valid time interval for that model. However, while on the time selection bar, the model's validity is expressed in UTC, in the warning messages there is a time zone applied to the validity dates and sometimes the time zones are different (e.g. SIFM vs CHAOS-5). I suggest to use UTC also in the warning messages.

![sifm](https://cloud.githubusercontent.com/assets/20207042/21233267/e25e304a-c2ee-11e6-9390-e600a6ba48b5.PNG)

![chaos-5](https://cloud.githubusercontent.com/assets/20207042/21233275/e6fccbb6-c2ee-11e6-98dc-73250093c28f.PNG)

**Comment by santilland** [comment]
Taking into account that the validity of the models are multiple years i think just showing the date (and not the hour/time) would simplify and reduce the message length and "resolves" the issue of UTC or local time.
I deployed this solution for now, but of course it can be changed to use the complete UTC string if preferred.

**Comment by lmar76** [comment]
In my opinion I would show also the time (in UTC). in this way, the information is equal to the data coverage on the time selection bar (which shows also fraction of a day). E.g. SIFM:

![image](https://cloud.githubusercontent.com/assets/20207042/21318272/c898fba0-c608-11e6-87eb-933d1d0c0e60.png)

**Comment by santilland** [comment]
You are right, it makes sense to display the same information, i updated the information message to use the complete utc time.
![image](https://cloud.githubusercontent.com/assets/4036819/21319070/f9bdc50a-c60b-11e6-935e-f2c858a70d94.png)
If you agree with the solution i will close the issue.

**Comment by lmar76** [comment]
I agree.
