### ISSUE TITLE
GUI not visible with Internet Explorer (v1.2 - staging)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#176]
Issue observed on v1.2 (staging)

I tried to access the staging instance with Internet Explorer v11.0.9600.18524 but after login the GUI was not loaded. After two minutes I have closed the browser.

![ie](https://cloud.githubusercontent.com/assets/20207042/21359640/2cd45874-c6dd-11e6-842e-d9e228dcf328.PNG)

**Comment by santilland** [comment]
I minor issue was introduced and not rechecked when updating the time slider. Number.isNaN was used instead of just isNaN. Number.isNaN is not supported by Internet Explorer. Now updated and working in staging.

**Comment by lmar76** [comment]
Tested again. Now it works. Thanks!

![image](https://cloud.githubusercontent.com/assets/20207042/21387711/2a02be82-c779-11e6-8b39-b5f795cab621.png)
