### ISSUE TITLE
Colour scale not visible with Safari

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#179]
A test has been executed with Safari browser selecting both MAGA_LR_1B and EFIA_PL_1B products. The MAGA_LR_1B color scale on the globe view is not visible (see screenshot).

![untitled](https://cloud.githubusercontent.com/assets/20207042/21450001/325569ec-c8f3-11e6-8123-8b719335d1c0.png)

**Comment by santilland** [comment]
Issue related to #197 also solved for safari browser. Closing issue.
