### ISSUE TITLE
Sub-setting Gauge

### ISSUE THREAD

**Issue by triebnigg** [ESA-VirES/WebClient-Framework#18]
**Intro:** Swarm (L1b) products are currently subset for rendering on map and analytics scatterplot. The number of observations which are excluded by the server is a combined function of (user selected)  extents of ToI and geographic area.

**Proposed enhancement:** A sort of dynamic gauge in the layer settings window could inform the user about the percentage of shown observations.

> Subsetting Gauge Example from http://iop.io/iopctrl

![logarithmic-gauge](https://cloud.githubusercontent.com/assets/12813866/14201387/e16aa5d8-f7f1-11e5-91aa-638d82937aa7.png)

**Comment by miktoki** [comment]
I think this would give connotations to performance, vehicles etc. 

If it needs to be shown, I think a 1 decimal number would be enough. That being said, while it is a cool feature, I am not quite sure how useful it is for the end user. Personally, I think that as long as it is documented somewhere relatively accessible with a couple of sentences about the sampling algorithms along (possibly) with an equation. 

This is an opinion, and I am open for discussion.

**Comment by triebnigg** [comment]
For V1.0 corresponding information will be given in the FAQ as documentation why the sampling depends on the spatio-temporal selection.

**Comment by santilland** [comment]
Ok, so in commit https://github.com/ESA-VirES/VirES-Server/commit/5b9aa5e3113c77d12324124858e433bdfd98ca4f we updated the FAQ section with information on subsetting.
I think we can close this ticket now and create a new ticket with possible evolution concepts in the future. Please let me know if you agree with this.
