### ISSUE TITLE
Possibility to define subsampling step when downloading

### ISSUE THREAD

**Issue by santilland** [ESA-VirES/WebClient-Framework#191]
For some use cases swarm data during a long time periods is wanted where the high frequency of data is unimportant as it is used to create coarse models.
Ideally they would like to download a specific parameter for the whole mission with a much lower rate then available from swarm.
We could think about integrating a subsampling factor in the download panel.
(As communicated by NH  Mar 24, 2017)

**Comment by pacesm** [comment]
Already implemented and deployed in production in v2.1.
