### ISSUE TITLE
Add to FAQ how visualization of bubble index is done in timeline

### ISSUE THREAD

**Issue by santilland** [ESA-VirES/WebClient-Framework#194]

**Comment by lmar76** [comment]
I would add also a note indicating that not all the probabilities are visualized on the map. There are some cases (e.g. Swarm Alpha, on 15/03/2016 between 20:00 and 20:30, probability 0.026) where the points are not represented on the map and the minimum value should be indicated.

![image](https://cloud.githubusercontent.com/assets/20207042/24869807/b28ae8b4-1e14-11e7-949b-0a082800596f.png)

**Comment by santilland** [comment]
I think that is a good idea, i will update the FAQ. While we are at it i realized having it as numbered list is a bit cumbersome when adding new questions which do not necessarily make sense to be appended but "grouped" thematically.
Would it be ok to remove the numbering?
The added entry to the FAQ could be:
Q: How does VirES visualize Bubble Index Data?
A: There are multiple aspects for visualization of Bubble Index data, firstly on the timeline not the product availability itself is shown (as with other products) but actually time events where the Bubble_Probability is equal or greater then 0.1. This allows to quickly find in time when there is an active bubble. In the Map Widget not all data points are shown (as with other products) but only those which have a probability above 0.1. The full retrieved data (which can be subset differently depending on the selected time and area) can be visualized in the scatter plot of the analytics panel (for all values).

What do you think of this text? Any changes you would consider?

**Comment by lmar76** [comment]
I think both text and the thematic groups are fine.

**Comment by santilland** [comment]
Closing issue as now information is also in production.
