### ISSUE TITLE
Colour scale not visible

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#197]
Issue observed on v2.0 - production server - Chrome browser

After login, the colour scale for MAG LR (default selection) is not visible (see screenshot):

![image](https://cloud.githubusercontent.com/assets/20207042/24908836/fe3591d0-1ec1-11e7-95b4-3ff56b64eaed.png)

Activating EFI PL layer, both the colour scales are still not visible.

![image](https://cloud.githubusercontent.com/assets/20207042/24908911/35a79884-1ec2-11e7-89fb-66e743021c6e.png)

The same issue has been detected selecting TEC and FAC layers (see screenshot)

![image](https://cloud.githubusercontent.com/assets/20207042/24909066/c640c726-1ec2-11e7-9df9-b2c11340ce06.png)

Deselecting and selecting again the "Legend" checkbox in the layer's settings, the colour scales appear.

The test has been repeated after cleaning the browser's cache but the problem persists.

**Comment by santilland** [comment]
Thanks for catching this, (i think) the issue has appeared for chrome with one of the newer versions, but it is an issue that was already present in firefox and safari (see #167 and #179) i reworked how the colorscales are generated and did some cleanup of events when loading a previous workspace which should increase performance (or computation load) when initializing the client.
It is deployed on staging but i am still doing some testing (but it seems to work as expected), please also have a look. If we agree we could do a minor bugfix "release" to production soon.

**Comment by lmar76** [comment]
I have tested on staging it with Chrome, Firefox and Internet Explorer and I did not see any occurrence of the issue. With Internet Explorer the interaction with the interface is very slow. I don't know if this is related with the new change. Could you please check?

**Comment by santilland** [comment]
I use for testing official windows virtual machines for IE11 and Edge, i tried adding more video memory for better performance, as far as i can see comparing staging and "production" i see no performance difference. It is true that the performance in internet explorer is not very good. At home with a good graphics card it also works as expected.
Do you see a difference between staging and production? The changes made really only change how the steps are done starting but i can't quite imagine it could change the performance while running normally.

**Comment by lmar76** [comment]
I have done some additional tests on the production server and I did not see any difference on the performance while using IE11 wrt staging server.

**Comment by santilland** [comment]
The original issue can be closed and i think also the discussions related are finished. I will close issue, if any other comments are remaining please feel free to comment.
