### ISSUE TITLE
FAQs - Apex Quasi-Dipole latitude and Magnetic Local Time (enhancement)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#199]
Following the request for information on the QD coordinates calculation (see email sent by from Frederic Pitout to feedback@vires.services on 03/04/2017), the answer to question 3 on the FAQs page "How does VirES evaluate the Apex Quasi-Dipole latitude and Magnetic Local Time?" should be improved to provide further information. E.g. adding a brief explanation like the one provided by Martin:

> VirES is using following formula to evaluate the QD latitude (lat_QD):
> 
> lat_QD = +/-acos( sqrt( (R_E + h) / (R_E + h_A) ) )
>
> where:
>   R_E is the mean Earth radius (6371.009 km)
>   h is the geodetic height above the reference ellipsoid
>   h_A is the geodetic height of the apex above the reference ellipsoid
>   and the sign given by the vertical component of the magnetic fields

also on QDLon and MLT and adding reference documents, e.g.:

> [1] Richmond, Ionospheric  Electrodynamics  Using Magnetic  Apex Coordinates, J. Geomag. Geoelectr., 47, 1995
> [2] Emmert et.al., A computationally compact representation of Magnetic‐Apex and Quasi‐Dipole coordinates with smooth base vectors, J. of Geophysical Research, vol. 115, 2010.

**Comment by santilland** [comment]
Information already added, closing issue. If other updates required please feel free to comment.
