### ISSUE TITLE
Window default resolution

### ISSUE THREAD

**Issue by triebnigg** [ESA-VirES/WebClient-Framework#20]
When I reduce the window in which I start-up VirES (split view) from full screen to a somewhat smaller size, then the histograms in the analytics pannel are quickly starting to overlap. A user will surely not protest about this but zoom out by an interactive setting of the browser resolution. 

**Question:** Can the system default resolution be configured/changed? I think a somewhat lower resolution (e.g. 75% of current setting) would be adequate and still produce a well readable display.

The enclosed screenshots where produced with reduced window size at 100% and 75% browser resolution. In the first case the overlapping histograms can be observed; in the second case, they get displayed fine.

**100%**
![2016-04-02 1](https://cloud.githubusercontent.com/assets/12813866/14227056/d383f94e-f8f3-11e5-9f2e-3bbd5aebae94.png)

**75%**
![2016-04-02 2](https://cloud.githubusercontent.com/assets/12813866/14227063/f0e0a686-f8f3-11e5-86a1-c5d3a1d77925.png)

**Comment by santilland** [comment]
There are some approaches that can be taken but in general it is a bad idea to try to configure the browser of the user, maybe he is using already a different zoom level for any number of reasons, imposing our own would not be good.
All elements in the site are reactive, but there is just a limit of how much can be shown, if the user sees he has space issues he could zoom out. This should anyway only happen on relatively low resolution displays.

**Comment by triebnigg** [comment]
Actually the test which lead to this issue was performed on my Windows with a zoom level for Windows Apps set to 175%. if it is set to 150% or less, all information can be seen properly. No further action required here.
