### ISSUE TITLE
VirES EEF product - missing 'flags' parameter

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#200]
The 'flags' parameter is missing from VirES EEF downloaded product (both CDF and CSV formats).

**Comment by santilland** [comment]
Thank you for the ticket, the download parameters are configurable from the client and it seems the Flag attributes were not added correctly, can be solved easily, will be done for next minor release

**Comment by santilland** [comment]
Missing flags were introduced, also available in production, closing issue. If any related problems are found please feel free to comment.
