### ISSUE TITLE
VirES FAC product - missing 'Flags', 'Flags_B', 'Flags_F', 'Flags_q' parameters

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#201]
The 'Flags', 'Flags_B', 'Flags_F', 'Flags_q' parameters are missing from VirES FAC downloaded product (both CDF and CSV formats).

**Comment by santilland** [comment]
Thank you for the ticket, the download parameters are configurable from the client and it seems the Flag attributes were not added correctly, can be solved easily, will be done for next minor release

**Comment by santilland** [comment]
Flags are now also available in production, closing issue. Feel free to comment if any related problems are found.
