### ISSUE TITLE
Date filter on Download Manager

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#202]
After internal discussion, we would like that the initial (default) time selection in the Download Manager is equal to the time selection (up to seconds) on the time slider.

**Comment by lubojr** [comment]
I believe that this is already implemented on production.  Could you please confirm?

**Comment by pacesm** [comment]
It seems to me that right now the download time selection by default selects whole days rather then the exact time selection as requested by this ticket.

@lmar76 Do I understand your ticket correctly that you would like to replace the (currently default) selection by whole days by selection by exact time (which is now optional)?

**Comment by lmar76** [comment]
@pacesm I don't remember how was the behaviour when the ticket was created but I think that the current one is fine. Activating the "specify time"  box, the time selection is automatically filled. I think the issue can be closed.

**Comment by pacesm** [comment]
OK, I'm closing the issue.
