### ISSUE TITLE
Show/Hide filters issue

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#205]
Issue observed on version 2.0 (operational).

The following test has been performed with Chrome browser:

1. click on "Hide filters" button -> the filters (histograms) disappear but the size of the plot area is not increased and the "Show filters" button is not visible:

![chrome1](https://cloud.githubusercontent.com/assets/20207042/26686566/a0c7200a-46ed-11e7-8732-05567f05ae54.PNG)

2. Close the browser and reopen VirES webpage -> VirES workspace appears with the plot area enlarged and the "Show filters" button visible:

![chrome2](https://cloud.githubusercontent.com/assets/20207042/26686640/deca62ae-46ed-11e7-9c6e-14e13d45b1e2.PNG)

3. Click on the "Show filters" button -> the plot area size is decreased but the filters area and the "Hide filters" button do not appear:

![chrome3](https://cloud.githubusercontent.com/assets/20207042/26686716/1f5f1b66-46ee-11e7-9608-7e0ea6748331.PNG)

4. Close the browser and reopen VirES webpage -> the original layout is restored: filters area and "Hide filters" button visible:

![chrome4](https://cloud.githubusercontent.com/assets/20207042/26686728/281588e4-46ee-11e7-9431-2d53cc5d3cf3.PNG)

The same test has been executed with Firefox and Internet Explorer showing the same results.

**Comment by santilland** [comment]
Thank you for the report, i can reproduce it and will look into solving the problem.
I will keep you updated here.

**Comment by santilland** [comment]
Solved now in staging, once deployed to production issue will be closed.

**Comment by lmar76** [comment]
Tested with Chrome, Firefox and IE: the show/hide buttons work properly.
