### ISSUE TITLE
Download link not protected

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#206]
Issue observed on release 2.0.

Currently it is possible to copy the product's download URL (from the Download button) and download the product from a different client without login (e.g. I tried with "wget" on a different PC). Since we are currently protecting the access to the VirES workspace, why don't protect also the products download URL?

**Comment by pacesm** [comment]
@lmar76

**Comment by lmar76** [comment]
After internal discussion, ESA decided to leave the download mechanism as it is to give priority to other features.

Please, close the issue.

**Comment by pacesm** [comment]
Understood.
