### ISSUE TITLE
Globe map not visible

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#208]
Issue detected on version 2.0 (operational and staging) with browsers: Internet Explorer v11 and Safari.

The globe map in the web client is not visible:

- Internet Explorer 11

![capture](https://user-images.githubusercontent.com/20207042/27278806-c701844c-54e2-11e7-8abd-2c79540b181c.PNG)

- Safari

![safari](https://user-images.githubusercontent.com/20207042/27278829-d76b453e-54e2-11e7-991d-0d96aa4fc437.jpg)

**Comment by santilland** [comment]
There were some changes to the map background access strategy (not related to vires) which seemed to work correctly, but IE seems to have some issues with redirects.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8680109/
We updated the used url to make sure a redirect is no longer used. It should work again now.
