### ISSUE TITLE
Issue on resume session message

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#209]
This issue has been detected on version 2.0.

The message indicating the resume of the previous session appears covered by the one indicating the successful login (see screenshot). Moreover, the two messages disappear very soon and, since the reset button does not work, it is not possible to reset the session to the default.

Please note that if the login has been already performed in the previous session (e.g. user already authenticated with Google) the resume session message duration is longer than in the previous case and both the link and the reset button work as expected.

![untitled](https://user-images.githubusercontent.com/20207042/27279504-182a6206-54e5-11e7-8068-b336ea5ec0f9.png)

**Comment by santilland** [comment]
They are two "different" messaging systems, one coming from the registration system and the other from the client. I added a check to see if these messages overlap and re-position them accordingly. I will mark the issue as closed, please feel free to add any comment.
