### ISSUE TITLE
Timeslider above map

### ISSUE THREAD

**Issue by Schpidi** [ESA-VirES/WebClient-Framework#21]
The timeslider used to look like floating above the map. In order to centre the globe at start this has been changed. I propose to let a designer evaluate to place the timeslider at the bottom of the page without floating effect.
![vires](https://cloud.githubusercontent.com/assets/482265/14247409/3f8ee15a-fa6e-11e5-8691-8c0b71c1c8f7.png)

**Comment by pacesm** [comment]
@santilland Is this still relevant?

**Comment by santilland** [comment]
All in all i would say we can close this for now.
Still, I think Stephan's point is valid, in the sense that it would might be interesting to look at designing the timeslider differently, not as a "floating" element but more as a panel at the bottom, maybe even with the option to hide it, if wanted. But that might be a topic to be done as part of the D3.Timeslider library in general and not necessarily here.

**Comment by lubojr** [comment]
Allowing to disable/hide the timeslider completely on demand is going to be done in this Quarter for mundi (for reference) https://seeed.fr.atos.net/seeed-project/eox-cws/-/issues/52

I will probably do it outside of D3.Timeslider component though

**Comment by santilland** [comment]
Yea, that also makes sense as the timeslider just lives in a container div, and we can do with that whatever we want depending on the project.
So, i guess the question is, if we want to change the style for VirES.

**Comment by pacesm** [comment]
Yes, the point is valid but I see no pressure to revamp the visual style of the client. I'm closing the ticket for now.
