### ISSUE TITLE
Initial time window (improvement)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#210]
After internal discussion we would like to set the initial (default) time window to the interval:

(*current-date* - 7days 00:00:00,  *current-date* - 7days 23:59:59)

where *current-date* is automatically set.

Is it possible?

**Comment by santilland** [comment]
yes, it should be relatively easy to do, can we assume that the longest period without new data will be 7 days?
It is not really "resetting" things but it makes sense to not have a fixed date.

**Comment by santilland** [comment]
As the solution is not complicated i added it directly and deployed it to staging. My approach was to select 1 day 7 days before the current date and show a time span of -+ 1 week, so the timeslider shows 2 weeks, when the user resets the application.
This feels like a good approach.

**Comment by santilland** [comment]
This is available in staging and will be deployed to production in release v2.1. Closing the issue, if anything else to report feel free to comment on the issue.
