### ISSUE TITLE
Kp/Dst not visible on the time bar

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#211]
Issue detected on operational instance v2.0.

The Kp/Dst plots on the time bar are not visible with Internet Explorer and Safari. Only the Y-axis appears.

Internet Explorer:

![ie](https://user-images.githubusercontent.com/20207042/27470534-b7dafda8-57f4-11e7-98c4-d27d1d23431f.PNG)

Safari:

![kp dston safari](https://user-images.githubusercontent.com/20207042/27470544-cb549e3e-57f4-11e7-8dd1-5f4862aad390.png)

**Comment by santilland** [comment]
Thank you for the issue report, found the problem being that IE handles parsing of date strings differently. Will be integrating the solution to staging soon.

**Comment by santilland** [comment]
Solution deployed to staging
