### ISSUE TITLE
Filters cancel other filters in globe view - Staging + production

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#217]
Any filter applied together with the any of QDLon, QDLat and orbit number filters will not be applied on the Globe View. There seems to be a hiearchy of filters (QDLon>QDLat>orbit number>all others) such that filters of lower "priority" are ignored. This does not affect downloaded data or the analytics view.

This is observed across browsers and both in the staging and production instance. 
![orbit_number_world](https://user-images.githubusercontent.com/17086561/31294383-f8b2cb74-aada-11e7-878f-2a559a36dd0d.png)

**Comment by santilland** [comment]
Thank you for catching that, the application of the filters on the globe had a little issue where filters could "overwrite" the previous filter. Should be solved in #d2d9b4788e16bf1cde2bd46fb3b68ecb889f9c8b (now on staging)

**Comment by miktoki** [comment]
Since this also affects the production instance (QDLat and QDLon), I think something should be done there soon as well.

**Comment by santilland** [comment]
If everything goes as planned we will be releasing this version latest in two weeks, so i think the best will be to do just one release with all fixes. If it was planned for a later release i would also suggest to do it beforehand.

**Comment by miktoki** [comment]
Fixed on Staging
