### ISSUE TITLE
Starcraft histogram filter - staging

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#218]
It is possible to add "Starcraft" to the histogram panel. This filter filters away all data in the analytics view, but none in the Globe view and data download. Any selection on the filter will override all other filters as described in #217 

Filter range seems to be from 0 to 254, while the ticks labels only indicate "NaN". When selecting a range on the histogram, the stationary limit value updates instead of the limit displayed near where the mouse is. 

Having a starcraft histogram filter is in itself questionable, as it is already implemented in Layers, and would not be as flexible as that one because histogram filters only allow one region contiguous region to be selected(ie. to select A and C one would have to select B, as it would be in between).

**Comment by santilland** [comment]
The "Spacecraft" parameter should not have been exposed, it was introduced to the data in order to also be included in the CDF, but it was not intended for use for filtering. Removed it as possible filter attribute in d2d9b4788e16bf1cde2bd46fb3b68ecb889f9c8b (now staging)

**Comment by miktoki** [comment]
Sorry, cache might have not been removed
