### ISSUE TITLE
Orbit number histogram integer tick labels - staging

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#219]
Currently the orbit numbers use the floating point exponential format (ie. 1.75e+4) as it is a relatively large number. It is often difficult to find any changes in the ticklabel across days, and it might make it difficult to find a specific orbit number. 

It would be more helpful to have integer ticks to accurately pinpoint an orbit number, especially as the data is also encoded as such, and the histogram bars are displayed in integer intervals. This should also take up less (visual) space (5 digits until roughly Jan 2031).

**Comment by santilland** [comment]
Updated how number formatting is done in the analytics panel, with the possibility to specify formatting in the configuration. (Available on staging)
