### ISSUE TITLE
Colormaps reversed

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#222]
Some of the colormaps being displayed are the reverse of what one should expect, ie, "ylgnbu" displays "ylgnbu_r" (ie blue,green,yellow). The same is true for "ylorrd"->"ylorrd_r" and "coolwarm"-> "bwr_r". 

The last one funnily enough more closely resembles what colours correspond to cool and warm stars, but we normally interpret blue as negative and red as positive.

**Comment by santilland** [comment]
You are right, it seems that there was a confusion when creating the scales and some seem to use the reverse version, i am working on getting them in order.

**Comment by santilland** [comment]
Issue should be solved now with commit 6b1aaefc00123738bbbced55f1a779d74e1707e5
Deployed to staging.

**Comment by miktoki** [comment]
the colormaps are now not reversed. What matplotlib defines as "coolwarm" is different from the coolwarm in vires (which looks like matplotlib's "bwr"). This could cause confusion, but the issue is solved.
