### ISSUE TITLE
Difference of large coefficient parts of models - staging

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#223]
When attempting to display the model difference between SIFM and CHAOS-6 with coefficient range [71,110] one would expect (assuming there is no contribution from SIFM to the displayed model as this exceeds SIFM coefficient range) to get a negative of CHAOS-6. 

This may be related to #221 . In addition to not displaying the same features as when displaying CHAOS-6, there is an unexpectedly large amplitude of the difference. F(CHAOS-6) has range [0 nT,0.5 nT], while F(SIFM - CHAOS-6) has range approximately [-35 nT,20 nT].

 
![vires_services_screenshot 1](https://user-images.githubusercontent.com/17086561/31430880-7318e3a4-ae72-11e7-910f-e4d9c019da11.jpg)
![vires_services_screenshot 2](https://user-images.githubusercontent.com/17086561/31430897-7f8a406a-ae72-11e7-80ef-ae62bf3b6f40.jpg)

**Comment by miktoki** [comment]
The initial values for the range of values of the colorbar, are much closer to what one would expect, but do not correspond to what is being displayed. This leads me to think that perhaps the problem only lies in the code for displaying the model difference on the globe.

**Comment by santilland** [comment]
It seems the issue is related to #221 as you thought. If we look at lower altitudes such as 0km the result of original CHAOS-6 with coefficients [70,110] is quite similar to difference of SIFM [70-110]
![image](https://user-images.githubusercontent.com/4036819/31488134-1c8d493c-af3d-11e7-9640-d8e7fd522ce6.png)
![image](https://user-images.githubusercontent.com/4036819/31488149-24b42446-af3d-11e7-85a1-8173a3600d5e.png)
I think it is easier to see because the residual values are higher and can be seen on top of the difference that adds values for SIFM (although it should not)

**Comment by miktoki** [comment]
The difference CHAOS-6 - SIFM should be identical to CHAOS-6 at coefficient ranges above what SIFM can show (ie lower range above 70) as SIFM at these values is a "null map". It is not identical, although its max/min values are similar and it has features in similar coordinates. Its average is also very different:
SIFM:
![sifm](https://user-images.githubusercontent.com/17086561/31662939-a97bbdea-b340-11e7-8042-0301b02bdf2e.png)
CHAOS-6:
![chaos-6](https://user-images.githubusercontent.com/17086561/31662958-c270e29e-b340-11e7-85ff-7b845445c6cf.png)
CHAOS-6 - SIFM:
![chaos-6-sifm](https://user-images.githubusercontent.com/17086561/31662971-c91dbd2e-b340-11e7-8add-d8710362a6fd.png)

**Comment by santilland** [comment]
Ok, there were two issues related to the problem, one as mentioned previously (#221) and the other that the coefficients were not being sent correctly in the request for the model difference calculation, which also has been solved now, so now it looks as is expected - like this:
![image](https://user-images.githubusercontent.com/4036819/31672100-e5798424-b35b-11e7-976b-235a30b79361.png)
![image](https://user-images.githubusercontent.com/4036819/31672101-e8f822d6-b35b-11e7-9c67-99c33732bb25.png)
