### ISSUE TITLE
colorbar model difference long numbers - staging

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#224]
When choosing a non-default coefficient range for the model values, the colorbar ticks will often have unrounded numbers (ie with trailing 9s), making it difficult to read.

![screenshot from 2017-10-11 11-34-57_mod](https://user-images.githubusercontent.com/17086561/31433158-ba636274-ae78-11e7-9343-b5a00551eea9.png)

**Comment by santilland** [comment]
It is s bit difficult to get the appropriate scale steps for any combination. I updated how the tick steps are calculated adding a rounding factor that is accuracy dependent, so it works also with very small ranges. This was included in commit 7ab17945792ea2bde3b699b7874ab1316ba7d1e1 and released on staging
