### ISSUE TITLE
Donwload Error Handling

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#23]
In case on an download error, the client does not check the error message returned by the server and always displays following message to the user:

> Error Downloading Data! The result set requested contains over 430000 mesaurements, please refine your filter criteria.

even if the reasons of the failure is completely different and it is misleading the user.

It is understood that the current implementation of the data download does not allow proper error checking. Therefore the message should indicate that the actual reason of the failure might completely different. Following wording is more appropriate:

> Error Downloading Data! This might be caused by too many records being selected. Please refine your filter criteria.
> Should this issue persist, please, check the browser log. 

**2016-04-18 UPDATE:**
The download works again and the error message has been changed as suggested above. However, it is still not technically possible to inform the user about the reason of the download failure. The user has to check the browser network log to see the error details.

**Comment by santilland** [comment]
Text was updated, but the underlying issue still needs to be investigated

**Comment by santilland** [comment]
The CSRF issue was solved in commit 4ee73b98f0c28d6fbb9482872a4d7890acb4be62.
I think there is still some discussion to be had about the donwload functionality.

**Comment by santilland** [comment]
Now that we introduced asynchronous processing we show possible processing error message in download panel. Once file has been produced it can be downloaded through normal browser file download mechanism. Thus i will be closing this issue as i consider it solved through the new used method. If there are any comments on this please feel free to do so.
