### ISSUE TITLE
Model's fieldlines not always visible

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#231]
Issue observed on version 2.1

Sometimes the model's fieldlines are not visible. The issue has been observed for all the models. One of the cases to reproduce the issue is the following:

1. click on the reset button
2. change view to "globe"
3. select one of the models (e.g. CHAOS-6) and deselect the MAG-LR layer
4. select an area
5. select fieldlines parameter form the model settings -> the fieldlines appear
6. click on "Clear Selection"
7. move globe and/or change zoom and select a new area -> the fieldlines do not appear anymore

![image](https://user-images.githubusercontent.com/20207042/33373006-572d7b96-d500-11e7-96f2-606ac0c9bbb1.png)

**Comment by santilland** [comment]
It seems i found the problem in a if statement where it checks if the fieldline parameter is used or not. 
The change has been deployed to staging for further testing.

**Comment by lmar76** [comment]
Tested on staging with Chrome, IE and Firefox: the issue does not appear anymore.

**Comment by santilland** [comment]
Moved to operations, closing ticket, feel free to comment for any related things.
