### ISSUE TITLE
Kp & Dst indices are not displayed in Firefox

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#24]
Kp & Dst indices are not displayed by the time-slider in Firefox. The same feature works in Chrome.

**Comment by santilland** [comment]
This was an issue of firefox not handling the Date object creation as chrome does, adapted accordingly the timeslider library and integrated it into the webclient in commit e3a5e487bc2a232e05543206d79dff2389db9019
