### ISSUE TITLE
Zoom and pan issues

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#240]
Problem observed on staging instance.

While trying to zoom and/or pan the scatterplot, the scales and limits of the x and y axis (and also the grids) are updated but the plot remains unchanged.

1. Reset the workspace -> default settings are applied.
2. Select a time range containing MAG-L data -> the plot of F parameter is displayed:

![image](https://user-images.githubusercontent.com/20207042/38254344-603f949c-3759-11e8-876e-a126ea35350e.png)

3. Try to increase the zoom level -> the axis scales and limits are updated but the plot is unchanged (compare the axis scales between the following plot and the previous one):

![image](https://user-images.githubusercontent.com/20207042/38254418-899cdfac-3759-11e8-9479-71bbe58d176f.png)

4. Pan the scatterplot ->  the axis limits are updated but the plot is unchanged (compare the axis scales between the following plot and the previous one):

![image](https://user-images.githubusercontent.com/20207042/38254529-d0a023dc-3759-11e8-9662-910ace5dd8a0.png)

5. Apply a filter -> the measurements out of the filter's rage are displayed in grey and the **zoom level of the plot is changed**:

![image](https://user-images.githubusercontent.com/20207042/38254619-0c42bada-375a-11e8-90ce-0c18523f1ae1.png)

6. Reset the filters -> all the measurements are displayed with the same color and the zoom level is unchanged:

![image](https://user-images.githubusercontent.com/20207042/38254721-45b54ef4-375a-11e8-9d6d-799b7001853f.png)

7. Try to decrease the zoom level -> the axis scales and limits are updated but the plot is unchanged (compare the axis scales between the following plot and the previous one):

![image](https://user-images.githubusercontent.com/20207042/38254767-5dbba7d2-375a-11e8-8682-9b319f85a7d1.png)

**Comment by santilland** [comment]
Issue was introduced in latest version of the plot library, it happens because it tries to update the second y axis and when none is available it runs into an error.
Issue was solved and will be added to the next update.

**Comment by santilland** [comment]
Solution is now deployed on staging.

**Comment by santilland** [comment]
I will close the ticket now, further checks were also introduced to make sure either the left or right y axis is being used before trying to render or update them. Please comment if any related issues arise.
