### ISSUE TITLE
Missing physical unit from default label on X axis

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#241]
Issue detected on staging instance.

The default label on Y axis contains the physical unit of the selected parameter, e.g. F[nT]. The default label on the X axis does not contain the physical unit:

![image](https://user-images.githubusercontent.com/20207042/38255180-6e7cbdf8-375b-11e8-89fa-6b4ec0d732b2.png)

**Comment by santilland** [comment]
Unit has been added, newly deployed on staging, will close the ticket directly, if there are any comments please feel free to do so.
