### ISSUE TITLE
Empty plot in case of not available data

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#242]
Issue observed on staging instance.

If no data is available for the selected area/time-range, an empty plot (i.e. containing only axes and labels) is displayed:

![image](https://user-images.githubusercontent.com/20207042/38255337-e1213816-375b-11e8-81cd-e6fe123a4b60.png)

In the previous version, the analytic panel is empty and a warning message is displayed:

![image](https://user-images.githubusercontent.com/20207042/38255448-1393c084-375c-11e8-9b50-7b94a5895e00.png)

**Comment by santilland** [comment]
Data format changed a little with the new update and checking for empty data was not done correctly, this has been updated and pushed to staging.
Now the warning message is shown when no data is available.

**Comment by santilland** [comment]
The changes are available at staging, after some further testing everything seems to work as expected, i will close the ticket now, if any other related issues appear please feel free to comment.
