### ISSUE TITLE
Timestamp not visible on Y-axis

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#248]
Issue observed on v2.2 (staging)

After changing the Y-axis parameter to "Timestamp" the plot is not visible anymore. E.g.: plot Timestamp vs Latitude, S/C-A, MAG-L, 01/05/2016

![image](https://user-images.githubusercontent.com/20207042/40051261-695875a6-583a-11e8-8f1e-d7f630832169.png)

Please note that this is possible on v2.1 operational instance (see below).

![image](https://user-images.githubusercontent.com/20207042/40051322-9ab15f5a-583a-11e8-93a0-25822b165e41.png)

**Comment by santilland** [comment]
Thank you for spotting that, looking at getting it working again

**Comment by lmar76** [comment]
I agree.
