### ISSUE TITLE
Kp & Dst index display in the time-slider

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#25]
The Kp and Dst should not consume layer space in the time-slider as they are displayed as the overlay graph.
The graph overlay should be then displayed over the layers' products bars.
See the screen-shot below ...

![screen-shot-0110](https://cloud.githubusercontent.com/assets/4050019/14315891/33f926e6-fc00-11e5-92b5-0dd368343491.png)

**Comment by triebnigg** [comment]
And actually the text on the vertical axes for the Dst and Kp graphs are impossible to read.

**Comment by pacesm** [comment]
@triebnigg There are actually two problems:

1. The Y-axes of the indices should not be rendered over each other. They should be next to each other or one on the left side and the other on the right side of the time-slider.
2.  The Y-axis of the Kp index has too many ticks and the numbers overlap. They are not readable even if the Dst index is not displayed.

**Comment by santilland** [comment]
Timeslider library was updated to create more readable. Number of ticks was reduced (2) and the placement of the scales was corrected (2). It was also made sure that lines and scales are painted over other timeline elements. This was introduced to the Webclient in commit e3a5e487bc2a232e05543206d79dff2389db9019
