### ISSUE TITLE
Y-axis not visible when parameter's value is 0

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#250]
Issue detected on v2.2 (staging).

When the parameter's value is 0 (e.g. F for satellite C, Bubble probability), the Y-axis (label, ticks and grid) is not visible  (see examples below).

![download 1](https://user-images.githubusercontent.com/20207042/40125709-d90ec624-592b-11e8-8852-a84b820bae81.png)

![download 2](https://user-images.githubusercontent.com/20207042/40125719-df112cba-592b-11e8-806e-0960fa543a45.png)

On v2.1, the Y-axis with a default scale is always visible (see below).

![vires_services_plot_rendering 1](https://user-images.githubusercontent.com/20207042/40125789-0d89b9fe-592c-11e8-9c69-1c82cce2460a.png)

![vires_services_plot_rendering](https://user-images.githubusercontent.com/20207042/40125794-115e01e8-592c-11e8-8705-c10917d635ce.png)

**Comment by santilland** [comment]
Solved in new deployment on staging, y axis is shown when all values are 0.
Minor change to shown range, it now goes from -1 to 1 centering the 0 line in height which i think looks better.
![image](https://user-images.githubusercontent.com/4036819/40234218-43343a2c-5aa6-11e8-9aac-e395cb4871e7.png)

If agreed i would close the ticket, please let me know.

**Comment by lmar76** [comment]
I agree.
