### ISSUE TITLE
Overlapped "Reset filters" and "Add filter" button

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#252]
Issue detected on v2.2 (staging).

The "Reset filters" and "Add filter" buttons appear to be overlapped. The issue has been detected using Chrome, Firefox and Safari browsers only on macOS (see below).

<img width="1792" alt="schermata 2018-05-18 alle 15 10 09" src="https://user-images.githubusercontent.com/20207042/40236456-e399b2a6-5aad-11e8-92f6-8ea4fa76b0bc.png">

<img width="1792" alt="schermata 2018-05-18 alle 15 13 26" src="https://user-images.githubusercontent.com/20207042/40236512-1af47c9a-5aae-11e8-96aa-1079b20c5edc.png">

![schermata 2018-05-18 alle 15 14 29](https://user-images.githubusercontent.com/20207042/40236531-3078cc2e-5aae-11e8-9ccb-56d097e3f02a.png)

**Comment by santilland** [comment]
I was only able to reproduce this when changing the zoom level of the browser and only in firefox (not yet tested in safari). I tested different resolutions and browser windows sizes, is this still and issue?
