### ISSUE TITLE
Error message appearing while opening Download Manager

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#253]
Issue observed on version 2.1 (operational).

While opening the Download Manager, just after clicking on Download button, an error message appears (see screenshot).

![image](https://user-images.githubusercontent.com/20207042/40350267-976e9c3a-5da9-11e8-968f-7fbb409f1d77.png)

**Comment by santilland** [comment]
After looking at the problem it seems there was a small synchronization problem when shortly switching to the backup server to update the machine, where the created jobs were not synchronized to the other machine. In theory by clicking on "Process & create link" new processes should be created that overwrite the not correctly synced processes. We will look into checking how this happened.

**Comment by eox-cs1** [comment]
Syncing of processes were correctly performed at the DB level, but syncing of generated data was not correctly performed on machine-to-machine level. This resulted in "retrieving data errors". 
Problem has been solved and has been fix implemented. 
I recommend closing this issue.

**Comment by lmar76** [comment]
Another occurrence of the issue has been observed right now on the operational platform (v2.2) trying to create a custom product. In this case, the  error messages appears and it is not possible to download the product (the progress indicator remains at 0%).

![image](https://user-images.githubusercontent.com/20207042/41164287-12d3c7b2-6b3b-11e8-9230-f221e8fefe7c.png)


Product details:
- MAG LR data, satellite A, 2016-05-01
- Latitude, Longitude, Timestamp, Radius, MLT, QDLat, QDLon, OrbitNumber, SunAzimuthAngle, SunDeclination, SunHourAngle, SunRightAscension, SunZenitAngle

**Comment by eox-cs1** [comment]
Switching to the fall-back server and back, to upgrade to version 2.2, has interfered with the syncing of the user generated wps processes and the information about the wps processes managed in the user DB. This led to some entries in the DB with no corresponding wps processes on the hard-disc. 
We have cleaned-up those non-active  DB entries and both, wps processes on hard-disc and entries in the DB are in sync again. The described error should therefore not occur again.

**Comment by pacesm** [comment]
The problem was solved in v2.2. The ticket will be closed.
