### ISSUE TITLE
F10_INDEX - scatterplot not visible when changing view from Split Screen to Analytics

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#254]
Issue observed on v2.2 (staging).

1. Select satellite A, MAG LR data, 01/05/2016, F10_INDEX parameter -> the scatterplot of F10_INDEX parameter appears.

![image](https://user-images.githubusercontent.com/20207042/40366966-a91cea0c-5dd8-11e8-9d65-f8d13d1d47b8.png)

2. Select analytics view -> the scatterplot is not visible anymore.

![image](https://user-images.githubusercontent.com/20207042/40367097-e2064610-5dd8-11e8-86b5-4016970b9087.png)

**Comment by santilland** [comment]
There was an initiation order issue when switching views, was solved and deployed to staging.

**Comment by lmar76** [comment]
It works.

**Comment by pacesm** [comment]
@lmar76 This was deployed in production already in the September 2018 release (v.2.2.1).

I consider this issue solved and I will close the ticket.
