### ISSUE TITLE
Timestamp modified with local timezone

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#255]
Issue observed on v2.2 (staging).

The Timestamp value shown in the list of parameters visualized when the users clicks on a measurement in the analytics area is modified with the local timezone (i.e. it is not the original Timestamp). E.g. S/C-A, 01/05/2016, F vs Timestamp plot: the first measurement should have timestamp 2016-05-01T00:00:00Z but the timestamp is updated with a local time GMT+2: 

![image](https://user-images.githubusercontent.com/20207042/40430693-fd3c74ae-5ea5-11e8-8387-e576b2c29f57.png)

On the operational platform, the correct timestamp is visualized:

![image](https://user-images.githubusercontent.com/20207042/40430798-386b9e60-5ea6-11e8-8333-29074f67c23b.png)

**Comment by santilland** [comment]
Timestamp is now shown as previously done (deployed to staging), will close the ticket directly, if there are any further comments please do so here.
