### ISSUE TITLE
List of parameters - order changed

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#256]
Issue detected on v2.2 (staging).

The list of parameters visualized when the user clicks on a measurement in the scatterplot has been compared with the one visualized on previous (operational) version. In the previous version, they are visualized in "logical order" i.e. spacecraft, timestamp, coordinates, indices, etc. e.g. for MAG-L data:

id: Alpha
Spacecraft: A
Timestamp: 2016-05-01T00:00:00.000Z
Latitude: 20.902874
Longitude: 102.148136
Radius: 6822430.74
F: 35912.5961
F_error: 0.0482
Kp: 30
Dst: -2
QDLat: 14.758007
QDLon: 175.238052
MLT: 7.02823639
OrbitNumber: 13666
SunDeclination: 15.1403478
SunRightAscension: 38.6257118
SunHourAngle: -77.1237102
SunAzimuthAngle: 79.9220715
SunZenithAngle: 72.8964701
B_resAC_N: 20.4980909
B_resAC_E: 54.4676012
B_resAC_C: 50.1533595
B_VFM,X: 24710.4244
B_VFM,Y: 588.6228
B_VFM,Z: -26052.4991
B_error,X: 0.2185
B_error,Y: 0.2533
B_error,Z: 0.2234
B_N: 30945.6047
B_E: -651.629
B_C: 18210.6889

![image](https://user-images.githubusercontent.com/20207042/40432425-f95edcce-5ea9-11e8-83b3-d0c21546d839.png)

In the new version, this order has been changed and it is more difficult to find the desired parameter:

SunAzimuthAngle: 79.92207150999668
SunHourAngle: -77.12371019214291
Dst: -2
OrbitNumber: 13666
F_error: 0.0482
Timestamp: Sun May 01 2016 02:00:00 GMT+0200 (W. Europe Daylight Time)
QDLat: 14.758007049560547
SunRightAscension: 38.62571178494717
F: 35912.5961
Longitude: 102.1481362
Kp: 30
MLT: 374.5144348144531
QDLon: 175.23805236816406
SunZenithAngle: 72.89647014899452
Latitude: 20.902874
SunDeclination: 15.140347841807538
F10_INDEX: 93.5999984741211
Spacecraft: A
Radius: 6822430.74
id: Alpha
B_N: 30945.6047
B_E: -651.629
B_C: 18210.6889
B_error,X: 0.2185
B_error,Y: 0.2533
B_error,Z: 0.22340000000000002
B_VFM,X: 24710.4244
B_VFM,Y: 588.6228
B_VFM,Z: -26052.4991
B_resAC_N: 20.498090871722525
B_resAC_E: 54.46760124006062
B_resAC_C: 50.15335947971471

![image](https://user-images.githubusercontent.com/20207042/40432596-5dee0c3c-5eaa-11e8-8b20-be01b92f2361.png)

**Comment by santilland** [comment]
Looking how the parameters were ordered previously it was more or less a coincidence of how the data was handled. The data is handled differently now which reorders the parameters.
I have now sorted the parameters in the tooltip alphabetically to have a constant method for ordering, it has been deployed to staging, please let me know what you think of this approach.

**Comment by lmar76** [comment]
It's fine with me.
