### ISSUE TITLE
Reset graph zoom button covering axis label

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#257]
Issue detected on v2.2 (staging).

Sometimes the "Reset graph zoom" button covers the label indicating the maximum value of the parameter represented on Y-axis (see figure). Is it possible to improve the position?

![image](https://user-images.githubusercontent.com/20207042/40433614-b29633ca-5eac-11e8-9496-c157dc8148c1.png)

**Comment by santilland** [comment]
The easiest would be to move the reset button below the save button, what do you consider?

**Comment by santilland** [comment]
![image](https://user-images.githubusercontent.com/4036819/40475919-06b9ebf4-5f43-11e8-8e5d-e25f2c99c07a.png)

**Comment by santilland** [comment]
Deployed it to staging as it is a very minor style change, let me know if we should revert the change

**Comment by lmar76** [comment]
I like it :-)

**Comment by santilland** [comment]
Then lets leave it like that :) , i'll close the ticket
