### ISSUE TITLE
Found differences between MLT values

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#259]
Issue detected on version v2.2 (staging).

I have downloaded the following custom product:

MAG-L, spacecraft A, 01/05/2016: Timestamp, Latitude, Longitude, Radius, MLT, QDLat, QDLon, OrbitNumber, SunAzimuthAngle, SunDeclination, SunHourAngle, SunRightAscension, SunZenithAngle

both from staging and operational platforms and compared the results and I have found differences in the MLT values (see attached excel file). Perhaps the issue is related to #258 .

[other_comparisons.xlsx](https://github.com/ESA-VirES/WebClient-Framework/files/2039208/other_comparisons.xlsx)

**Comment by pacesm** [comment]
This looks like a bug. I'll have a look on it.

**Comment by pacesm** [comment]
@lmar76 Can we close this ticket?

**Comment by lmar76** [comment]
I can't repeat the test due to issue #253.

**Comment by lmar76** [comment]
Yes!
