### ISSUE TITLE
Layers widget controls 

### ISSUE THREAD

**Issue by triebnigg** [ESA-VirES/WebClient-Framework#26]
Suggestion for some minor enhancements related to the individual layer selection and mouse pointer behaviour:

from left to right:
- tick box: mouse pointer should change to selection symbol (finger on hand)
- Layer name text: currently mouse pointer changes to insert/edit symbol although nothing can be edited (neutral arrow pointer would be adequate)
- move layer up/down button: mouse pointer symbol is OK but I suggest to swap place of the up/down button with the colour square on its right - group the two controls next to each other 

also,  tooltips would be nice, such as:
-  tick box: "select layer"
- move layer up/down button: "move layer up/down"
- open settings button: "open layer settings"

**Comment by triebnigg** [comment]
Actually an additional idea could be to provide also tooltips by mouse-over the layer name text. e.g. for models the tooltips could give the full name of the model and its validity epochs.

**Comment by pacesm** [comment]
@santilland Is this still relevant?

**Comment by santilland** [comment]
I would also say we could close this. Some points are no longer relevant as the layers panel changed, and some points were already implemented.
The one thing that could be extracted as possible enhancement is adding of tooltips, but not sure how you would like to keep track of possible enhancements, maybe one ticket could be created with a checkbox list with minor enhancements?

**Comment by pacesm** [comment]
ok, let's close it then.
