### ISSUE TITLE
Model evaluation outside the model validity period.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#262]
The currently deployed operational version extrapolates model coefficients for times outside the model validity period leading to completely wrong results which can be mistakenly considered as correct by the users.

The correct behaviour is to evaluate models for times within the validity only and return `NaN` values outside of it.

The issue was already solved in the upstream and it is ready to be deployed to production.

**Comment by lmar76** [comment]
Is the fix already deployed to staging? I have executed a test with SIFM in a time range *outside* the time validity of the model but I can still visualize the residuals between F and the model. This should not be possible if the values returned by the model are `NaN` .

**Comment by pacesm** [comment]
I am sorry, was not deployed to `staging` (just on the DISC machine). I've just did the deployment and you can test it now.

The calculated model residuals should be set to `NaN` for times outside the model validity period (try the visual analytic or download). On staging, however, the data cover only limited period of time and, I guess, the only model whose validity ends in this period is the MMA_SHA_2C. 

As far as the globe view is concerned, the client displays model values for the closest valid time and it should display a warning that the time selection is outside of the model validity (also see related #263)
```
  time_displayed = max(validity_start, min(validity_end, time_selected))
```
Note that this behaviour was chosen as the "old" magnetic models did not change much over the time and perhaps a little outdated result was be acceptable.

**Comment by lmar76** [comment]
Tested on staging. It works.

**Comment by pacesm** [comment]
@lmar76 FYI, the warning is covered by a separate ticket. See https://github.com/ESA-VirES/WebClient-Framework/issues/263

These two are closely related but still separate issues. This ticket concerns the server-side bug while the #263 is a client-side one.
