### ISSUE TITLE
FAC AC not visualized in the analytics view (major)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#264]
Issue detected on operational server (v2.2).

Selecting FAC layer and single satellite data (e.g. A) the FAC is visualized on the globe map, time slider and analytics view:

![image](https://user-images.githubusercontent.com/20207042/41359342-938b9158-6f2a-11e8-8faf-bad2a66997e0.png)

If the AC checkbox is selected in addition to A, the FAC AC product's coverage is visualized on the time slider but the product is not visualized on the globe and in the analytics view. The analytivs view shows only the FAC A plot:

![image](https://user-images.githubusercontent.com/20207042/41359769-820bc62c-6f2b-11e8-9b95-a88dcdfc8b3a.png)

**Comment by santilland** [comment]
There was an issue with the id handling for the non spacecraft of derived data, should be solved and has been deployed to staging. Could add it to next smaller bug update to production.

**Comment by lmar76** [comment]
Tested on staging. It works, thank you!

**Comment by lmar76** [comment]
It works also on the operational server.

**Comment by pacesm** [comment]
@lmar76 Already fixed deployed in production with the September 2018 release (v2.2.1). I am closing the ticket.
