### ISSUE TITLE
Add filter button: missing parameters

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#268]
Issue detected on v2.2.

In the analytics panel there is a list of "predefined" parameters to be used as filters, e.g. (for MAG-L): F, B_N, B_E, B_C, Dst, QDLat, MLT. If the user removes one or more of them from the filter panel, he can't add them anymore because they are not indicated in the list appearing when clicking the "Add filter" button.

**Comment by pacesm** [comment]
Fix deployed on staging.

**Comment by lmar76** [comment]
Tested.
