### ISSUE TITLE
Firefox has issues loading handlebar templates

### ISSUE THREAD

**Issue by santilland** [ESA-VirES/WebClient-Framework#27]
When loading handlebar templates firefox produces errors in the console:
- junk after document
- not well-formed

This does not seem to affect the behaviour in any way but to maintain a clean load we should look into this

**Comment by pacesm** [comment]
@santilland Is this still relevant?

**Comment by santilland** [comment]
Errors still appear in console log, but again, it is because firefox expects them to be xml in this case and they are not, it does not have any negative effect apart from cluttering the console log, i think it has some relevance.

**Comment by pacesm** [comment]
Yes cluttering the console log is annoying but if it does no harm I prefer to close it.

We try to support different browses on best effort basis and and, IMO, this is below the threshold.
