### ISSUE TITLE
Can't change map projection in Globe View

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#271]
Issue detected on v2.2.

The following test has been executed:

1. Access the web interface and click the Reset button -> interface in default status
2. Change view to Globe -> globe view visualized showing 3D globe
3. Click the button to change the map projection -> nothing happens
4. Close the web interface page and reopen it -> web interface restored to globe view
5. Click the button to change the map projection -> the 3 options appear and it is possible to change the map projection.

**Comment by pacesm** [comment]
Confirmed.
Does not depend on a particular browser. I observe the same behavior Chrome and Firefox.

**Comment by pacesm** [comment]
Fix deployed on staging.

**Comment by lmar76** [comment]
Ok, it works.
