### ISSUE TITLE
Support for the new EFIx_LP_1B product.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#272]
`EFIx_LP_1B` replaces the `EFIx_PL_1B` which has been discontinued.

**Comment by pacesm** [comment]
See also https://github.com/ESA-VirES/VirES-Server/commit/36e50b7ca51324534c519058c171d6d6bca42cbb and 5fd39b545bddb8d2ebf46139ccc0a284a597b371

**Comment by lmar76** [comment]
Selecting the new "EFI LP" product, the default parameter on the Y-axis is not set. In the previous implementation ("EFI PL") the default parameter was "n". Now we could select "Ne".

**Comment by pacesm** [comment]
@imar76 Thanks for the report. We'll have a look at the issue.

**Comment by pacesm** [comment]
@imar76 the problem has been solved and the fixed client deployed on staging

**Comment by pacesm** [comment]
Released and deployed in production.
