### ISSUE TITLE
List of parameters not visible in Split Screen mode (regression)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#273]
Issue observed on v2.2.1 and Chrome browser v69.

1. Click on Reset button->the initial default split screen view is visualized.
2. Click on a measurement point -> the list of parameters does not appear.

The same test has been executed with Firefox v61.0.1 and IE v11 and the issue is not present.

**Comment by pacesm** [comment]
The following screenshot has just been taken form Chrome v69 ...

![image](https://user-images.githubusercontent.com/4050019/46290143-527f4a80-c58b-11e8-9df7-5b51ed44ed29.png)

The info box showing the parameters of the selected measurement point is clearly visible.
I am not able to reproduce the reported problem and all seems to work as expected.

**Comment by lmar76** [comment]
I have reinstalled the Chrome browser. Now the info box is visible. Sorry for the inconvenience.

**Comment by pacesm** [comment]
No problem. I am closing the ticket now.
