### ISSUE TITLE
date selection widget "behind" plot

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#274]
Issue detected on v2.2.1.

In analytics view mode, with filter panels disabled, in some cases the date selection widget appears "behind" the plot and it is not possible to change the year.

![image](https://user-images.githubusercontent.com/20207042/46283125-cd3c6b80-c573-11e8-93b4-bdc4f714f442.png)

**Comment by constantinius** [comment]
Hm, this looks like a simple z-index issue. I'll have a look and see if I can quickly fix it

**Comment by constantinius** [comment]
I cannot reproduce this in our testing environment, so it may very well already be fixed and included in the next version.

**Comment by pacesm** [comment]
I have just reproduced this issue on both testing and staging using different browsers and this issue is definitely **not fixed** in the VirES-Client.
![image](https://user-images.githubusercontent.com/4050019/46291899-ec48f680-c58f-11e8-9e6b-87773bc8c98f.png)

**Comment by pacesm** [comment]
Fix deployed on staging.

**Comment by lmar76** [comment]
Tested.
