### ISSUE TITLE
Confirmation email containing unresolved placeholders

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#275]
The confirmation email sent to the user after performing the self-registration contains unresolved placeolders (i.e. '%s'):

```
Hello from VirES for Swarm!

You're receiving this e-mail because user demo at https://%s has given yours as an e-mail address to connect their account.

To confirm this is correct, go to https://vires.services/accounts/confirm-email/NjE1:1g7gzk:NAsXQkdkpORgzOtX3zBZtXQysPI/

Thank you from VirES for Swarm!
https://%s
```

**Comment by lmar76** [comment]
@pacesm email sent. Thank you.

**Comment by lmar76** [comment]
Tested again. It works.

>>>Hello from staging.vires.services!
>>>
>>>You're receiving this e-mail because user test7 at staging.vires.services has given yours as an e-mail address to connect their account.
>>>
>>>To confirm this is correct, go to https://staging.vires.services/oauth/accounts/confirm-email/xxxxxxxxxx/
>>>
>>>Thank you from staging.vires.services!
>>>staging.vires.services

**Comment by pacesm** [comment]
This issue is tracked by the [v3.2.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/8) and can be closed.
