### ISSUE TITLE
Missing Absolute_VTEC, Elevation_Angle (enhancement)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#283]
This issue to trace a possible future enhancement to support the 'Absolute_VTEC' and 'Elevation_Angle' parameters, introduced in the TEC products on July 2017.

**Comment by lmar76** [comment]
For the time being, could you please add it to the evolution features list (i.e. the Excel file)? Thank you.

**Comment by pacesm** [comment]
@lmar76 Sure, I'll do.

**Comment by pacesm** [comment]
@lmar76 
FYI, we implemented basic support for the Absolute_VTEC and Elevation_Angle parameters (already deployed on staging). Any special visualization requirements can be discussed/implemented later.

**Comment by pacesm** [comment]
Fixed. Already deployed in production.
