### ISSUE TITLE
Missing physical unit from axis label selecting B_[NEC]_res_model

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#284]
Selecting B_[NEC]\_res_*model* on X or Y axis, the physical unit (i.e. [nT]) is not displayed.

The issue has been detected for the following models: MCO_SHA_2x, MLI_SHA_2x, MIO_SHA_2x, MMA_SHA_2x, CHAOS-6-MMA-x.

**Comment by pacesm** [comment]
Fix deployed on staging.

**Comment by pacesm** [comment]
Deployed in production in v2.2.3.

**Comment by pacesm** [comment]
Sorry, yet to be deployed in v2.3.0.

**Comment by lmar76** [comment]
It seems they are visible now.
