### ISSUE TITLE
Missing physical unit from axis label selecting GPS_Position and LEO_Position from TEC

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#288]
Selecting GPS_Position_[XYZ] or LEO_Position_[XYZ] on X or Y axis, the physical unit is not displayed.

**Comment by pacesm** [comment]
Confirmed.
Observed in production too.

**Comment by pacesm** [comment]
Fixed in https://github.com/ESA-VirES/WebClient-Framework/commit/ebd1bfb6cef2988be8b2df615559aa1d34837304

Already deployed on staging.

If you see kilometers as the `GPS_Position_[XYZ]` units instead of the correct meters please reset the client to reload the configuration.

**Comment by pacesm** [comment]
Fixed. Already deployed in production.
