### ISSUE TITLE
F10.7 data in the downloaded product files

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#289]
As already done with Kp and Dst auxiliaries, also F10.7 should not be included in the downloaded products.

**Comment by pacesm** [comment]
@lmar76 OK, this should be trivial to fix.

**Comment by pacesm** [comment]
@lmar76 The issue was solved and the fixed version deployed on staging.

**Comment by pacesm** [comment]
Fixed. Already deployed in production.

**Comment by pacesm** [comment]
By removing the F10.7 from the downloads we made the validation of the MIO models impossible.

The F10.7 values are used in the scaling factor of the MIO_SHA_2* models. With no option to retrieve the exact values used for the model evaluation the model calculation cannot be reproduced and hence decided whether the downloaded model values are correct or not.

Also note that it might be useful to have all the indices as downloadable parameters. The indices may be used in filters but without a possibility to download the actual values we cannot tell whether the filters work correctly.

I do not know what was the actual reason behind the decision to completely remove the indices from the downloads but I propose we make them downloadable as optional parameters.

**Comment by lmar76** [comment]
The reason behind the indices removal is that these auxiliary data are retrieved from external sources (i.e. non-ESA) and their distribution is permitted only for some specific users (e.g.: CalVal, VirES) and not to the entire community. This means that VirES application can use this data to perform calculations (e.g. model's evaluation) but it has been decided to not allow the VirES users to download them (i.e. only to visualize them). Please note that this is the same policy adopted on the Swarm FTP server: the generic user cannot download auxiliary data. However, if there are particular needs to include these data into the downloaded products, we can discuss them during the next VirES meeting.
