### ISSUE TITLE
Parameter displayed in the legend for 2D plots

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#298]
In case of 2D plots (VIR-060) the GUI should display the parameter represented with the colorscale because it depends on the X and Y parameters.

**Comment by pacesm** [comment]
@lmar76 
Just to confirm that I understand this requirement correctly ...

When a third variables is added and displayed as a colormap, you would like to change the default label in the legend from the variable which defines the Y position, as it is done right now:

![screen-shot-0156](https://user-images.githubusercontent.com/4050019/54374770-1f83cb80-4680-11e9-8353-6c60d2101465.png)

to the name of the third variable:

![screen-shot-0157](https://user-images.githubusercontent.com/4050019/54374911-61ad0d00-4680-11e9-8e5d-aa5b43a03a05.png)

Am I right? Or is there more to be done?

**Comment by lmar76** [comment]
Yest, it is right.

**Comment by lmar76** [comment]
Tested.
