### ISSUE TITLE
Privace statement

### ISSUE THREAD

**Issue by Schpidi** [ESA-VirES/WebClient-Framework#30]
It might be a good idea to add a privacy statement page explaining what we're going to do with personal user data and how we keep them safe and link to it from both sign up forms as well as the profile editing page.

**Comment by miktoki** [comment]
Could that be included in the VirES terms of service (eg. similar to [Google](https://www.google.com/intl/en/policies/terms/)):

> Your Content in our Services
>
> Some of our Services allow you to upload, submit, store, send or receive content. You retain ownership of any intellectual property rights that you hold in that content. In short, what belongs to you stays yours. 

Which refers to the privacy statement page:

> You can find more information about how Google uses and stores content in the privacy policy or additional terms for particular Services.

**Comment by triebnigg** [comment]
The "VirES Service Terms" are being discussed internally - therefore, this issue is closed.
