### ISSUE TITLE
Magnetic Model label in the globe view (enhancement)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#300]
Issue detected on v2.3.0.

In the previous versions, if the user selected a magnetic model, the name of the model  and the selected parameter was reported above the color scale. E.g.:

![image](https://user-images.githubusercontent.com/20207042/53822243-a4c7fb80-3f6f-11e9-8764-fa8b6025078a.png)

In the new version, the label reports the text "Magnetic Model".:

![image](https://user-images.githubusercontent.com/20207042/53822299-c5905100-3f6f-11e9-9440-164c73cb1433.png)

We propose to change the label to the previous value (i.e. visualize the real name of the selected magnetic model) if the user selects a single model and to leave the generic "Magnetic Model" only if the user selects (i.e. adds or subtracts) more magnetic models.

**Comment by lmar76** [comment]
Please, extend the requirements also to the analytics plot (F_res_<model_name> or B_NEC_res_<model_name>) and to the warnings visualized when the time selection is outside the model's time validity.

**Comment by pacesm** [comment]
@lmar76 FYI, there is a new version of the client deployed on staging which tries to address this issue.

For single models, the full model name is displayed and the selected range of the degrees is indicated

![screen-shot-0162](https://user-images.githubusercontent.com/4050019/55616024-2f7b6080-5791-11e9-88b6-98687fc19072.png)

In case of composed models, the long expression is truncated to fit the limited space below the colorbar.

![screen-shot-0163](https://user-images.githubusercontent.com/4050019/55616037-36a26e80-5791-11e9-8ad6-e46fb461474d.png)

**Comment by lmar76** [comment]
Could it be possible to find a solution for the composite model? It is fine to have the concatenated names but if the string is truncated it is not possible to understand from the picture what is represented in the color code map.

**Comment by pacesm** [comment]
I see two possible ways how we could show the full composed model expression:
1) showing the full expression broken to multiple lines. This is however not completely trivial as the legend is rendered as SVG and not HTML.
2) show the full expressions as a tool-tip on mouse over.

Which one do you prefer?

**Comment by lmar76** [comment]
I think the second one is fine. Thank you.

**Comment by lubojr** [comment]
An attempt to fix the issue has just been deployed to staging. 
Label images for Composed models with more than 1 component now show only name instead of full Model expression, which can than be seen as a tooltip on mouse over. 
When model has only one component, the full model expression is shown in the label.

**Comment by lmar76** [comment]
@lubojr fine with me.

**Comment by pacesm** [comment]
This feature has been already deployed to staging and it is scheduled for the 3.0.0 release. See https://github.com/ESA-VirES/WebClient-Framework/milestone/2

I propose to close the ticket.

**Comment by lmar76** [comment]
@pacesm fine with me
