### ISSUE TITLE
Add the "x" icon to close the "Config" window (enhancement)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#301]
Issue detected on v2.3.0.

Currently the user must click on the "Config" link to close the "Config" window. This is not very intuitive. Could you please add the "x" icon on the top right corner (e.g. see windows to select the parameter on x or y axis) to close the window?

**Comment by santilland** [comment]
Added the x button also to this panel.

**Comment by pacesm** [comment]
deployed on staging

**Comment by lmar76** [comment]
Ok, it works!

**Comment by pacesm** [comment]
The feature has not been deployed in production yet and it was already fixed in staging.

The ticket can be closed.
