### ISSUE TITLE
Rename "Apply colorscale" label (enhancement)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#302]
Could you please rename the "Apply colorscale" label to "Add third variable"?

![image](https://user-images.githubusercontent.com/20207042/53871434-8c51f280-3ffc-11e9-850b-f0e46edb1642.png)

**Comment by santilland** [comment]
![image](https://user-images.githubusercontent.com/4036819/54132836-37a3e280-4415-11e9-9d81-67bcd1316ec2.png)
Label renamed in staging, ticket could be closed.
