### ISSUE TITLE
Multiple plots not saved

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#305]
Issue detected on v2.3.0.

The following plot with multiple parameters has been created on the GUI: B_N, B_E, B_C vs Latitude (see screenshot below).

![image](https://user-images.githubusercontent.com/20207042/53970748-ac1c1000-40fb-11e9-89b4-1b7ee33a9b28.png)

In the images downloaded, only the first parameter (in this case, B_N) is visible:

![vires_for_swarm_20190307](https://user-images.githubusercontent.com/20207042/53970882-fd2c0400-40fb-11e9-9df4-0f821f48d8b9.png)
 
The issue has been detected selecting all the available sizes and formats with Chrome, Firefox and IE.

**Comment by santilland** [comment]
There was an issue with an array iteration which was taking only the first parameter in the saving process, this has been solved and deployed to staging.

**Comment by lmar76** [comment]
Ok, it works!

**Comment by pacesm** [comment]
This feature has not been deployed yet in production and it is already fixed in staging. The ticket can be closed.
