### ISSUE TITLE
Wrong Kp index values.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#312]
As it was explained to us by GFZ/GK and DTU/NiO, the _Kp_ values currently used in VirES are not the actual _Kp_ index values (from 0 to 9) but the _Kp_.10 values (from 0 to 90, i.e., _Kp_ multiplied by 10).

The source values shall be divided by 10 to get the correct _Kp_ index.

**Comment by pacesm** [comment]
fixed on staging

**Comment by lmar76** [comment]
Can you please limit decimal digits to avoid the following issue?

![image](https://user-images.githubusercontent.com/20207042/54287934-e3306c80-45a6-11e9-9d38-31210e1ccb3d.png)

**Comment by pacesm** [comment]
@lmar76 This is a problem of the plotting library unrelated to the actual _Kp_.  I moved this issue to a separate ticket #313

**Comment by lmar76** [comment]
Tested.
