### ISSUE TITLE
Fix decimal places to avoid floating point artefatcs.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#313]
The rendering of the tick labels in the AV plots should render the decimal numbers to fixed number of decimal places to prevent floating point round-off artifacts

![screen-shot-0155](https://user-images.githubusercontent.com/4050019/54289967-6ef7c800-45aa-11e9-9fcc-4eb92b8c091b.png)

**Comment by pacesm** [comment]
FYI, I am able to reproduce this issue in any browser simply by dragging the Y axis and moving it up or down.

**Comment by santilland** [comment]
Fix deployed to staging

**Comment by lmar76** [comment]
Ok, tested.
