### ISSUE TITLE
Latitude_periodic and QDLatitude_periodic not visible

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#321]
Issue detected on operational server (v2.3.0).

The plots `Latitude_periodic` vs `Timestamp` and `QDLatitude_periodic` vs `Timestamp` are not visible (see example below).

![image](https://user-images.githubusercontent.com/20207042/55243332-4d037400-523f-11e9-879c-e0bfa7ea44ef.png)

Please note that the same plot is visible on the staging platform:

![image](https://user-images.githubusercontent.com/20207042/55243424-850ab700-523f-11e9-97a2-bb2d0417bf97.png)

**Comment by pacesm** [comment]
@lmar76 I am sorry, apparently the orbit direction look-up tables were not properly initialized. The problem should be solved now.

**Comment by lmar76** [comment]
Ok, tested.

**Comment by pacesm** [comment]
Problem solved. I am closing the ticket.
