### ISSUE TITLE
Error while logging in via Linkedin

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#338]
The login via LinkedIn account is not possible: Internal Server Error.

**Comment by pacesm** [comment]
In confirm the issue.

The debugging reveals that the `LinkedInOAuth2Provider` gets `410 This resource is no longer available under v1 APIs` response from LinkedIn.

The issue might be related to https://github.com/pennersr/django-allauth/issues/2300.

Further investigation is needed.

**Comment by pacesm** [comment]
I investigated the issue and these are the findings:

1. So far VirES server has been using Linked-In OAuth2 API V1.
2. Linked-In OAuth2 API V1 had been deprecated for some time and it was recently dropped.
3. To support Linked-In we have to switch to Linked-In OAuth2 API V2.
4. The recent django-allauth versions do support OAuth2 API V2 (>=0.39.0) but they dropped support for DJango 1.8 (>=0.35.0)

Conclusion:
1. As a quick relieve we could disable the Linked-In option on the production machine.
2.  We cannot quickly fix this issue unless we upgrade the VirES server to Django 1.11 (a couple of days of testing would be required).
2. The new OAuth server, which is being finalized now and which is supposed to replace the VirES server social-network authentication, supports Linked-In OAuth2 API V2 (uses Django 2.2 and django-allauth 0.39.2)

**Comment by lmar76** [comment]
Thank you for the investigation. Do you have an estimation on when will be ready the new OAuth server you mentioned at point 3? If we don't have to wait too long I would skip the upgrade described at point 2 and go for the one at point 3.

**Comment by pacesm** [comment]
FYI, the OAuth server is already deployed on testing and I am currently integrating with the rest of the system. I expect it would be ready by the end of this week.

As far as the Django 1.11 upgrade is concerned, we will need to do it soon or later anyway. The Djnago 1.8 is no longer maintained and its support has been dropped by many libraries. But rather then to Django 1.11 we should plan an upgrade to Python 3 and Django 2.2.

**Comment by lmar76** [comment]
I agree with you. Anyway, could you please add this topic to the agenda for the teleconference of tomorrow?

**Comment by pacesm** [comment]
I'll do.

**Comment by pacesm** [comment]
The LinkedIn authentication works on the production machine again.
