### ISSUE TITLE
Safari 8 unable to reach landing page

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#34]
While Safari 9 (with OS X El capitan) seems to work, we have been unable to reach the vires landing page using Safari 8 (with OS X Yosemite). 

The root cause could be that SAFARI is having issues due to handshaking mechanisms with the server when attempting to establish SSH/TTL connection. 

Can you reproduce + could this be handled on the server side?

**Comment by Schpidi** [comment]
There was a misconfiguration of the `SSLCipherSuite` which should be fixed now. Could you please retry? Thanks

**Comment by miktoki** [comment]
It now seems to work :)
