### ISSUE TITLE
Rendering error with uploaded data

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#341]
This issue was detected on staging platform after uploading user data in CSV format. Unfortunately it happens sometimes and I could find the exact sequence of steps/conditions to reproduce it. However, in these cases, after uploading user data, the map rendering on the globe is interrupted and an error appears in the GUI (see screenshot below).

![Screenshot 2019-06-27 at 10 52 28](https://user-images.githubusercontent.com/20207042/60264836-78e8d100-98e4-11e9-8038-fdcc300200cb.png)

**Comment by pacesm** [comment]
@lmar76 can you send us the CSV via e-mail? Thanks.

**Comment by lmar76** [comment]
[ups20170301psec.sec.csv.zip](https://github.com/ESA-VirES/WebClient-Framework/files/3334844/ups20170301psec.sec.csv.zip)

**Comment by pacesm** [comment]
Thank you.
I checked the data and they are sane.
The error seems like a bug and it needs to be investigated.

**Comment by pacesm** [comment]
https://github.com/ESA-VirES/VirES-Server/commit/6e94129c5fc28adf5d0364ea4f76e0967d848b16 fixes the issue on the server-side.

a0d4fbf3e6772de7abf1085d5c85f2c54b7bbab9 and 2323a5235fd235944e453b80b829b9cb737ca377 fix the client

The fix has been deployed on staging.

**Comment by lmar76** [comment]
Ok, tested.

**Comment by pacesm** [comment]
The ticked is tracked by the [v3.1.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/4) and can be closed.
