### ISSUE TITLE
Model residuals not displayed for uploaded data.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#343]
When the uploaded data contain the `F` or `B_NEC` variable the server is capable of calculating the model residuals.

These residuals are displayed in the client, when the uploaded product and a regular `MAGx_LR` products are selected, as displayed in this screenshot:

![screen-shot-0185](https://user-images.githubusercontent.com/4050019/60945622-5eebbd00-a2ec-11e9-85ad-747115fd9991.png)

However, when only the uploaded data are selected, then the residual variables are no longer available:

![screen-shot-0186](https://user-images.githubusercontent.com/4050019/60946081-9313ad80-a2ed-11e9-87bf-8eac44acdc89.png)

The client should request the model residuals, when a model is enabled and the uploaded data contain the `F` or `B_NEC` variable.

(reported by @lmar76)

**Comment by lubojr** [comment]
Should be fixed in 5c607866fd05409eb35fe40f78fd93744de2e67d
Deployed to staging.

**Comment by pacesm** [comment]
@lmar76 I am not sure if you receive notifications for this ticket.
FYI, @lubojr solved the issue and the fix has been deployed to staging.

**Comment by lmar76** [comment]
Tested. It works!

**Comment by pacesm** [comment]
The issue has been assigned to the [v3.1.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/4) and can be closed.
