### ISSUE TITLE
Rendering error in case of filtered data

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#344]
Issue detected on v3.0.0 (operational) and v3.1.0 (staging).

Applying a filter on the selected data, the measurement points in the AV are displayed in grey. Selecting one of these points the following error is traced on the globe map and the rendering stops. E.g. satellite A, MAG LR, 04/07/2019:

![image](https://user-images.githubusercontent.com/20207042/61054023-fa655680-a3ee-11e9-8c64-d7716a609ee6.png)

**Comment by lubojr** [comment]
Thank you for spotting. It should be fixed and deployed to staging.

**Comment by lmar76** [comment]
Tested. It works.

**Comment by pacesm** [comment]
The issue has been assigned to the [v3.1.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/4) and can closed.
