### ISSUE TITLE
Client settings - import/export issues

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#347]
After applying the following selection: sat A, EFI data, 03/04/2019, Globe View changed to 2D, the GUI status was the following:

![Screenshot 2019-07-30 at 11 36 06](https://user-images.githubusercontent.com/20207042/62118929-dc3c9900-b2be-11e9-985e-2dba9dc6d67b.png)

The GUI settings have been exported (see attached [20190730T093612_vires_settings.json.zip](https://github.com/ESA-VirES/WebClient-Framework/files/3446191/20190730T093612_vires_settings.json.zip)) and the GUI restored to its default status (i.e. via Reset button).

The exported JSON configuration has been reimported trying to restore the GUI status before the initial export but the result was different (see image below):

![Screenshot 2019-07-30 at 11 36 49](https://user-images.githubusercontent.com/20207042/62119341-a2b85d80-b2bf-11e9-9b8c-32b8badf2362.png)

The zoom level and position in the Globe View is different from the previous one and the plot is not displayed.

**Comment by pacesm** [comment]
I confirm the issue. When I tried to load the configuration I got no plot either.

This seems like a bug. The actual JSON does not seem to contain any plot configuration
```
{
  "serviceVersion": "3.1.0",
  "mapSceneMode": "2dview",
  "selectedFilterList": [
    "F",
    "B_N",
    "B_E",
    "B_C",
    "Dst",
    "QDLat",
    "MLT",
    "F_error",
    "EEF",
    "FAC",
    "IRC",
    "Elevation_Angle",
    "Absolute_VTEC",
    "Absolute_STEC",
    "Relative_STEC",
    "Relative_STEC_RMS",
    "Bubble_Probability",
    "Te",
    "Ne"
  ],
  "timeSelection": [
    "2019-04-03T00:00:00.000Z",
    "2019-04-03T23:59:59.999Z"
  ],
  "timeDomain": [
    "2019-04-02T22:00:00.000Z",
    "2019-04-04T02:00:00.000Z"
  ],
  "productsConfiguration": {
    "SW_OPER_MAGA_LR_1B": {
      "visible": false,
      "outlines": false,
      "opacity": 1,
      "parameters": {
        "B_NEC": {
          "range": [
            15000,
            55000
          ],
          "colorscale": "jet"
        },
        "F": {
          "range": [
            15000,
            55000
          ],
          "colorscale": "jet",
          "selected": true
        },
        "B_NEC_resAC": {
          "range": [
            -600,
            600
          ],
          "colorscale": "jet"
        }
      }
    },
    "SW_OPER_EFIA_LP_1B": {
      "visible": true,
      "outlines": false,
      "opacity": 1,
      "parameters": {
        "Ne": {
          "range": [
            100000,
            200000
          ],
          "colorscale": "plasma",
          "selected": true
        },
        "Te": {
          "range": [
            1000,
            5000
          ],
          "colorscale": "portland"
        },
        "Vs": {
          "range": [
            -5,
            0
          ],
          "colorscale": "jet"
        },
        "U_orbit": {
          "range": [
            1500,
            3500
          ],
          "colorscale": "jet"
        }
      }
    }
  },
  "cameraPosition": {
    "position": [
      -19863920.004351005,
      -10002200.665195962,
      12756274
    ],
    "direction": [
      0,
      0,
      -1
    ],
    "up": [
      0,
      1,
      0
    ],
    "right": [
      1,
      0,
      0
    ]
  },
  "xAxisSelection": "Latitude"
}
```

**Comment by pacesm** [comment]
... as far as the Cesium camera is concerned, it seems that its position and orientation is correct but the view port size ("zoom scale") is different.

**Comment by pacesm** [comment]
@lmar76 FYI, we decided to track the Cesium 2D view issue in a separate ticket https://github.com/ESA-VirES/WebClient-Framework/issues/348.

**Comment by santilland** [comment]
The JSON is as expected, when some configuration parameters have not been changed from the default they are not added to the exported JSON.
There was an issue where the default selection was not being loaded in this case. 
This has been updated and pushed to staging. The provided configuration is working (in the AV view) now. The 2D camera position issue was separated into another ticket as written by pacesm.

**Comment by pacesm** [comment]
@lmar76 The issue should be fixed now. Please check.

**Comment by lmar76** [comment]
Concerning the plot visualisation, I confirm that the issue has been fixed. The Globe View is still affected by the same issue (#348)

**Comment by pacesm** [comment]
The issue has been assigned to the  [v3.1.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/4) and can be closed.

#348 remains open
