### ISSUE TITLE
Preserving state of the Cesium 2D view.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#348]
When using the Cesium 2D view, the view does not seem to be fully controlled by the camera parameter.

 The camera parameters preserve the right camera orientation and the 2D position on the lat./lon. plane but the zoom scale of the view-port is not preserved.

Zoomed 2D view **before saving**
![screen-shot-0188](https://user-images.githubusercontent.com/4050019/62129550-43fede00-b2d7-11e9-89af-65e03f0f4cbf.png)

2D view **after re-load**
![screen-shot-0189](https://user-images.githubusercontent.com/4050019/62129590-5bd66200-b2d7-11e9-9020-bb2b9d943cc8.png)

This issue is specific to the 2D only and it seems to be caused by the different handling of the 2D and 3D views (Globe and Columbus views) by Cesium.

The bug is unrelated to the saving method. It appears for both the file import/export and browser local-storage save.

Note: originally reported by @lmar76 in #347

**Comment by santilland** [comment]
For the 2d scene mode we needed to also save camera frustum information, this has been implemented and deployed to staging. Newly created save states will also correctly save the position in 2d scene mode of the camera.

**Comment by pacesm** [comment]
@lmar76 The issue should be fixed now. Please check.

**Comment by lmar76** [comment]
I tried to reload the exported JSON file but the image on the globe view is still different from the original one:

![Screenshot 2019-08-05 at 11 43 32](https://user-images.githubusercontent.com/20207042/62455648-25856080-b777-11e9-8a52-73530a715bb7.png)

**Comment by santilland** [comment]
Could you show an example image of the "original" and one of the "reloaded" status?
I always get the same map position i exported, i can't reproduce the issue.

**Comment by pacesm** [comment]
@lmar76 Please, export new a JSON. To preserve the state of the 2D view we had to add additional field to the JSON file which it not in the old file.

I am sorry for this confusion.

**Comment by lmar76** [comment]
I have repeated the test. I conform that the "original" view is restored.

Before:

![Screenshot 2019-08-05 at 12 29 22](https://user-images.githubusercontent.com/20207042/62458287-d0e4e400-b77c-11e9-99b2-59c5256e9e4c.png)

After:

![Screenshot 2019-08-05 at 12 30 08](https://user-images.githubusercontent.com/20207042/62458293-d5a99800-b77c-11e9-9236-f977a6f01e12.png)

**Comment by pacesm** [comment]
The issue has been assigned to the  [v3.1.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/4) and can be closed.
