### ISSUE TITLE
Single point selection in table broken when area has been selected on globe

### ISSUE THREAD

**Issue by Schpidi** [ESA-VirES/WebClient-Framework#35]

**Comment by santilland** [comment]
There was an issues of how the scene was cleaned removing the collection and creating an error that stopped opening of the information popup. A fix was introduced in commit 921aecfba95d50a26d37c6cd93eafb3df2edc827
Marking this issue as closed, please have a look and let me know if the issue persists on your end, if there are still any problems ill gladly reopen the ticket.

**Comment by Schpidi** [comment]
Works for me now. Many thanks.
