### ISSUE TITLE
Wrong reference to Swarm Plasma data

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#350]
In the "About" page, the reference to the Swarm Plasma data is outdated, i.e. it still indicates the old EFIx_PL_1B product (instead of the current EFIx_LP_1B one). Also the hyperlink should be updated.

![image](https://user-images.githubusercontent.com/20207042/62606595-e123cd00-b8fc-11e9-88f7-ea3d27d5b0d1.png)

**Comment by pacesm** [comment]
Thanks for spotting this out. We'll fix it.

**Comment by pacesm** [comment]
FYI, the same broken link is in the VirES for Swarm front page.

**Comment by pacesm** [comment]
@lmar76 Fixed and deployed on staging.

**Comment by lmar76** [comment]
Tested. It works.

**Comment by pacesm** [comment]
The issue has been assigned to the [v3.1.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/4) and can be closed.
