### ISSUE TITLE
Axis range controls not working

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#351]
I realized that in v3.1.0 there are two additional controls (the pencil icons) near the axis in the AV:

![image](https://user-images.githubusercontent.com/20207042/62607935-34971a80-b8ff-11e9-95e5-be95e07aa2e9.png)

I guess that they are needed to update the axis limits but they do not work (i.e. when I click on them, nothing happens).

**Comment by pacesm** [comment]
@lmar76 This feature was actually ported from Aeolus. It should be easy to fix.

**Comment by santilland** [comment]
The dependency to the analytics viewer library was updated, issue should be fixed now in staging

**Comment by lmar76** [comment]
It works. Thank you!

**Comment by pacesm** [comment]
The issue has been assigned to the  [v3.1.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/4) and can be closed.
