### ISSUE TITLE
Imported client state overriden by the default paramters.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#355]
It seems like the default product parameters override the saved/imported client state.

E.g., when the following client state

![screen-shot-0191](https://user-images.githubusercontent.com/4050019/62692943-d850fb00-b9d1-11e9-942a-f9eafde06ff0.png)

 gets saved into a JSON file ([B_NEC_residual.zip](https://github.com/ESA-VirES/WebClient-Framework/files/3481048/B_NEC_residual.zip))

it is then loaded as displayed in the following screenshot
![screen-shot-0190](https://user-images.githubusercontent.com/4050019/62693780-65e11a80-b9d3-11e9-94b6-3ade77803ed8.png)

Note the additional `F` plot and change of the `F_res_Model` line style.

This makes impossible to recall the client state as it was saved. This behavior is expected only when the product selection changes once the saved/imported client state was recalled i.e., when a user decided to change it, but not while the client is being initialized.

**Comment by santilland** [comment]
This seems to happen only when combining with residuals, it might have to do with how the data is loaded when combined with the model at startup, i will have a look when i get a chance

**Comment by santilland** [comment]
Fix implemented and deployed to staging

**Comment by pacesm** [comment]
Thanks. There has been a partial improvement. The `F` subplot is not created anymore.

However, the line style of the `F_res_Model` gets overridden (2px markers connected with lines changed to 8px with no line-connection).

**Comment by santilland** [comment]
Could you try reexporting your file, it seems the config for the F_res_Model was not saved in your exported file for some reason.
I re-exported it and at least with my export it seems to work fine.
[DS_B_NEC_residual.json.zip](https://github.com/ESA-VirES/WebClient-Framework/files/3485283/DS_B_NEC_residual.json.zip)

**Comment by pacesm** [comment]
Thanks. Indeed, the saved file did not contain the line style for the `F_res_Model`. Re-saving solved the problem.

The ticket can be closed now.
