### ISSUE TITLE
AV: hiding/showing filters incorrectly applies unapplied line style changes.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#356]
This is a tricky one.

1) start with a view like this
![screen-shot-0194](https://user-images.githubusercontent.com/4050019/62772619-5085f200-baa0-11e9-8d10-22c144b5a559.png)
[F.zip](https://github.com/ESA-VirES/WebClient-Framework/files/3485903/F.zip)

2) Click on the variable properties and change the line style but do not press the apply button. E.g., change symbol to rectangle, color to red, and connect points by lines:
![screen-shot-0195](https://user-images.githubusercontent.com/4050019/62772905-10733f00-baa1-11e9-9568-0447a4bfda64.png)

3) Now click the button below to show the filters
![screen-shot-0196](https://user-images.githubusercontent.com/4050019/62773129-a73ffb80-baa1-11e9-980f-cd93957468e7.png)

The change applies the not-yet-applied line style changes, but only in the AV plot. The legend does not change and neither does the client configuration. I.e., the change is neither saved nor exported.

In my opinion, the showing/hiding of the filter panel should not apply the not-yet-applied line-style changes. But if it does, then it should do it properly.

**Comment by santilland** [comment]
The changes in the settings panel were being set (in part) before pressing the apply button, and the apply button was triggering the re-rendering.
Now the changes are saved in an intermediate object and only applied once clicking the apply button.
This fixes the issue, it has been deployed to staging.
 (Make sure to clear browser cache to load latest version of dependency)

**Comment by pacesm** [comment]
Thank. It works.
