### ISSUE TITLE
AV: Plotting parameters rendered below the time-slider

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#357]
The plotting parameters are rendered below the time-slider which makes impossible to apply the changes.
![screen-shot-0197](https://user-images.githubusercontent.com/4050019/62774019-0272ed80-baa4-11e9-89e5-3dc1c82b24ef.png)

In such case, the filters needs to be displayed to get enough space to make the apply button reachable which leads to #356.

**Comment by santilland** [comment]
Z-index for settings panel was increased, now on top of timeslider. Deployed to staging.

**Comment by pacesm** [comment]
Thanks. It works.
