### ISSUE TITLE
AV panel crashes when changing product type

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#359]
The version currently deployed on staging contains following regression:

When changing product type the AV panel crashes. To reproduce the issue:

1) reset the client (MAG LR selected, F vs. Latitude displayed by the client)
2) deselect MAG LR
3) select EFI LP

While the globe displays the expected `Ne` variable, the AV panel gets stacked with the old data and becomes unresponsive. This happens for any product selection, i.e., it is not specific for the MAG LR or EFI LP products.

![screen-shot-0198](https://user-images.githubusercontent.com/4050019/62944432-f6a56500-bddc-11e9-9df9-e6e285cde906.png)

The browser console  reports following error
FF:
```
TypeError: n is undefined                          d3.min.js:3:5432
    extent d3.min.js:3
    value graphly.min.js:1
    E graphly.min.js:1
    value graphly.min.js:1
    value graphly.min.js:1
    reloadData AVView.js:1
    reloadData self-hosted:1013
    Backbone 3
    success DataController.js:1
    onreadystatechange httpRequest.js:1
```

Chrome:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.ao.extent (d3.min.js?bust=v3.10:3)
    at e.value (graphly.min.js?bust=v3.10:1)
    at E (graphly.min.js?bust=v3.10:1)
    at e.value (graphly.min.js?bust=v3.10:1)
    at e.value (graphly.min.js?bust=v3.10:1)
    at s.reloadData (AVView.js?bust=v3.10:1)
    at f (backbone.js:204)
    at s.trigger (backbone.js:144)
    at set (backbone.js:358)
    at success (DataController.js?bust=v3.10:1)```

**Comment by santilland** [comment]
Issue was introduced with solving of #355 and #347 the decision when defaults are loaded or not was changed and now all the cases should work as expected.
Solution deployed to staging.

**Comment by pacesm** [comment]
Thanks. I works.
