### ISSUE TITLE
AV: Y axis parameters list displayed behind the time bar

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#361]
When adding a new plot in the AV, if the plot area is near the time bar (see screenshot) the parameters list is displayed behind it.

![image](https://user-images.githubusercontent.com/20207042/63681886-fd79a200-c7f6-11e9-8cc1-bef7b4284bcb.png)

**Comment by santilland** [comment]
Z index of the settings panel was changed to be on top of the time slider.
Update was deployed to staging environment.

**Comment by lmar76** [comment]
Tested. It works. Thank you!

**Comment by pacesm** [comment]
The issue has been assigned to the [v3.1.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/4) and can be closed.
