### ISSUE TITLE
Globe View: IPDxIRR 2F settings

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#362]
The Parameter menu in the IPD IRR settings exceeds the the window border (see screenshot)

![image](https://user-images.githubusercontent.com/20207042/63774581-d944c080-c8dd-11e9-80b9-379d4d535ee7.png)

**Comment by pacesm** [comment]
@lmar76 
This was cased by very long titles of the IPDxIRR parameters.

The exceeding selection have been fixed (https://github.com/ESA-VirES/WebClient-Framework/commit/c3b430507c3b44ab726ae77bea5037865cb314f1) and deployed on staging.

**Comment by lmar76** [comment]
It works, thank you.

**Comment by pacesm** [comment]
The issue has been assigned to the [v3.1.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/4) and can be closed.
