### ISSUE TITLE
Products in the sources list outside of the requested time interval.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#365]
When, e.g., data from 2019-08-27 up to 2019-08-28 are requested data from 2019-08-27T00:00:00Z up to 2019-08-27T23:59:59Z will be correctly returned.

The sources list however contains also `SW_OPER_MAGA_LR_1B_20190828T000000_20190828T235959_0505_MDR_MAG_LR`
 (the next day) even though the requested time span does not overlap two days.

**Comment by pacesm** [comment]
should be fixed by https://github.com/ESA-VirES/VirES-Server/commit/b6842bafeb67805519d0d7cb7561f748ed91ea90

**Comment by pacesm** [comment]
fix deployed on staging

**Comment by lmar76** [comment]
I have repeated the test using the Download Manager:
- MAGA_LR_1B
- Dates: 2019-08-27T00:00:00Z - 2019-08-28T00:00:00Z

Downloaded file is: SW_OPER_MAGA_LR_1B_20190827T000000_20190828T000000_Filtered and does not contain the measurements at 2019-08-28T00:00:00Z 9as expected).

The sources list contains only SW_OPER_MAGA_LR_1B_20190827T000000_20190827T235959_0505_MDR_MAG_LR as expected.

**Comment by pacesm** [comment]
solved
