### ISSUE TITLE
Cannot load saved workspace.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#368]
Loading of the saved workspace fails during the initialization of the client. 
![screen-shot-0203](https://user-images.githubusercontent.com/4050019/65057986-c7ea5380-d973-11e9-878b-0fdf35c5b1db.png)

with
```
Uncaught Error: No such color scale 'diverging_1'
```

[MLI_SHA_2CD.json.zip](https://github.com/ESA-VirES/WebClient-Framework/files/3622357/MLI_SHA_2CD.json.zip)

**Comment by lmar76** [comment]
Tested. It works.
