### ISSUE TITLE
Orbit number to time range conversion fails.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#370]
Orbit number to time range conversion fails in the latest 3.1.0 release.

Quick fix is being produced.

**Comment by lmar76** [comment]
@pacesm sorry, I don't understand this issue. Was it something visible in the GUI? I believe it is fixed now but I don't know how to check it :-)

**Comment by pacesm** [comment]
@lmar76 This feature has not been (yet?) exposed via Web GUI. But it is available on the server and in the Pyhton client.

This function translates an orbit number or range of orbit numbers for a specified spacecraft into a time-interval. This helps selecting data by orbits.

**Comment by pacesm** [comment]
@lmar76 Example of time to orbit number and orbit number to time conversion using the Python client ```

**Comment by lmar76** [comment]
The ``get_times_for_orbits`` method works fine:

```
In [4]: req.get_times_for_orbits('A', 32612, 32613)                                                                     
Out[4]: 
(datetime.datetime(2019, 9, 12, 0, 52, 54, 583987),
 datetime.datetime(2019, 9, 12, 3, 59, 34, 5961))
```

The ``get_orbit_number`` raises an exception:

```
In [5]: req.get_orbit_number('A', dt.datetime(2019, 9, 12, 0, 52, 54, 583987))                                          
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-585e7c547a7c> in <module>
----> 1 req.get_orbit_number('A', dt.datetime(2019, 9, 12, 0, 52, 54, 583987))

/usr/local/opt/anaconda3/envs/swarm/lib/python3.7/site-packages/viresclient/_client_swarm.py in get_orbit_number(self, spacecraft, input_time)
    751         retdata = ReturnedDataFile(filetype="csv")
    752         response_handler = self._response_handler(
--> 753             retdata.file, show_progress=False
    754         )
    755         self._wps_service.retrieve(request, handler=response_handler)

AttributeError: 'ReturnedDataFile' object has no attribute 'file'
```

**Comment by pacesm** [comment]
@lmar76 Unfortunately, this is a bug in the VirES-Python-Client. Please install the latest version from the git repository master branch by
```
pip install --upgrade 'git+https://github.com/ESA-VirES/VirES-Python-Client@master#egg=viresclient'
```
or use VRE.

**Comment by lmar76** [comment]
Tested, it works. Thank you!

**Comment by pacesm** [comment]
Solved.
