### ISSUE TITLE
Reset View changing the zoom level of the globe map

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#371]
The Reset View button changes the zoom level of the globe map.

1. Click the "Workspace/Reset" button -> The default GUI status is applied (sat A, MAG LR, F vs latitude, split screen view)

![image](https://user-images.githubusercontent.com/20207042/65439441-733d5180-de27-11e9-80d0-45484dadfa08.png)

2. Click "Globe View" and then "Reset View" -> the zoom level of the globe map is increased.

![image](https://user-images.githubusercontent.com/20207042/65439486-83edc780-de27-11e9-9183-19e4e9ccb636.png)

The same issue is observed in Globe View mode.

**Comment by lubojr** [comment]
A change has been deployed on staging. A camera position in Reset View is now the same as the initial, when app is reset.

**Comment by pacesm** [comment]
solved in https://github.com/ESA-VirES/WebClient-Framework/commit/c602f3380c052a31f8924b1afd490c032813c438

**Comment by lmar76** [comment]
Tested. Thank you.

**Comment by pacesm** [comment]
solved
