### ISSUE TITLE
Regression: not possible to controll plot settings with "periodic latitudes" Y-axis

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#372]
When selecting `QDLatitude_periodic` or `Latitude_periodic` for the y-axis, the label for the variable is not displayed and thus it is not possible to set the plot parameters (e.g., to color the points by another variable).
![screen-shot-0204](https://user-images.githubusercontent.com/4050019/65941828-4216df80-e42c-11e9-958f-d4847186d7f8.png)

This regression has been observed in the currently deployed production version v3.1.0.

**Comment by pacesm** [comment]
Staging fixed in 858a2a02507ee58127dc99cc06e4ba30f5f102db.

Hot-fix branch #373 prepared to fix the production deployment.

**Comment by lmar76** [comment]
It works, thank you.

**Comment by pacesm** [comment]
Already deployed in production.
