### ISSUE TITLE
Position of time bar zoom control button

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#376]
Issue observed on v3.2.0.

New "buttons" to control the time bar have been introduced i this release. The two buttons controlling the time bar zoom level  ("+", "-") sometimes cover the time values reported below.

![image](https://user-images.githubusercontent.com/20207042/68374684-a1f85880-0145-11ea-9afb-e9e4cbe3c15b.png)

Could you please change their position (e.g. near the left/right arrows at the time bar borders or somewhere else)?

**Comment by lubojr** [comment]
That is a good point, thanks. There are several options, which we considered: 
1) Show all the control buttons (+-, arrows) only when mouse hovers over TimeSlider area. Location would stay the same.
2) Keep the +- signs center location, but stick them to the top border of TimeSlider.
3) Place them near the left/right of the arrow signs. - I am personally a bit against separating these two buttons by the whole width of the screen, as they might be used together and it would mean moving mouse a lot.
Which one would you prefer?

**Comment by lmar76** [comment]
I like option 1. Thank you

**Comment by lubojr** [comment]
Change has been deployed to staging.

**Comment by lmar76** [comment]
Tested, thank you.

**Comment by pacesm** [comment]
Solved.
