### ISSUE TITLE
Changing from 2D or Columbus view back to Globe view updates the zoom level of the globe map

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#378]
1. Click the "Workspace/Reset" button -> The default GUI status is applied (sat A, MAG LR, F vs latitude, split screen view)

![image](https://user-images.githubusercontent.com/20207042/68595309-7ce34d00-0499-11ea-97f3-94c25e15ddd7.png)

2. Change Globe View to 2D view or Columbus and then, change back to Globe View -> the zoom level of the globe map has changed.

![image](https://user-images.githubusercontent.com/20207042/68595334-8967a580-0499-11ea-9272-70d42a241244.png)

**Comment by lubojr** [comment]
Change has been deployed to staging.

**Comment by lmar76** [comment]
Tested. Thank you.

**Comment by pacesm** [comment]
solved
