### ISSUE TITLE
Selection tweaks

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#38]
When you press on  [Select Area], the text is replaced by "Deactivate". Maybe this is personal preference, but I find that changing the color and keeping the text  [Select area] is more intuitive. 

Additionally, when starting a selection, I find the toolbox a bit large. Is the text "drag to change rectangle rectangle" necessary when it makes it harder to see your bounded box (or that you have selected one at all)?

**Comment by miktoki** [comment]
It was also suggested that latitudinal and longitudinal lines could assist the user in making their bbox.

**Comment by miktoki** [comment]
At the very least, please change the selection text to not include "rectangle" twice.

**Comment by lubojr** [comment]
Tooltip size was decreased, double rectangle word gone - deployed to staging. Easier selection will be enabled through forms once #304 is merged.

**Comment by lmar76** [comment]
Tested.
