### ISSUE TITLE
Download request matching no data returns an error.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#385]
A download request matching no data an integer division error.
```
Error: integer division or modulo by zero
```
The expected behavior is to return an empty dataset.

**Comment by pacesm** [comment]
Fixed in https://github.com/ESA-VirES/VirES-Server/commit/99ba9307062f99b94d1709f278f61a0023b5cf5e

**Comment by pacesm** [comment]
The fix has been deployed on staging.

**Comment by lmar76** [comment]
Tested. Thank you

**Comment by pacesm** [comment]
The issue is tracked by https://github.com/ESA-VirES/WebClient-Framework/milestone/7 and can be closed.
