### ISSUE TITLE
Misleading message while the AV is being updated

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#386]
After resetting the workspace or changing product or time selection the following message is displayed in the analytics view: "_No data available for the current selection_", even if data for the given product is available (i.e. availability is displayed on the time bar), e.g.:

![Screenshot 2020-01-22 at 10 41 16](https://user-images.githubusercontent.com/20207042/72883517-bab7e980-3d04-11ea-9add-21e4012d542b.png)

After one or two seconds the AV and map are updated

![Screenshot 2020-01-22 at 10 41 34](https://user-images.githubusercontent.com/20207042/72883729-1e421700-3d05-11ea-9963-d38d29ee5e0a.png)

Even if the issue has a short duration, it could be a bit misleading for the user. It might be worth to introduce some kind of "animation" to indicate that the page is being updated.

**Comment by lubojr** [comment]
@lmar76 Thank you for reporting. The initial text of panel on app load is changed to Loading data. After that, it always either shows "No data available for current selection" or the AV Panel with Charts. Change happened in #389 and was deployed to staging. Would the current state be okay for you?

**Comment by lmar76** [comment]
@lubojr Yes, thank you!

**Comment by pacesm** [comment]
This issue is tracked by the [v3.2.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/8) and can be closed.
