### ISSUE TITLE
Model color scale not visible in the globe map

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#387]
Even if the "Legend" checkbox in the model's properties window is checked, the model color scale is not visible in the globe map.

![Screenshot 2020-01-22 at 17 44 41](https://user-images.githubusercontent.com/20207042/72914660-4b132000-3d3f-11ea-8dc0-9921e6c1d05b.png)

**Comment by lubojr** [comment]
Thank you for reporting. It was fixed in #388 and deployed to staging.

**Comment by lmar76** [comment]
Tested. Thank you.

**Comment by pacesm** [comment]
This issue is tracked by the [v3.2.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/8) and can be closed.
