### ISSUE TITLE
Columbus view / 2.5D  - add to tutorial 

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#39]
While the 2.5D map works, it requires the use of `Ctrl + mousedown` to really add any value. Could the use of the Columbus view be added to the tutorial?

**Comment by santilland** [comment]
The same functionality can be achieved by pressing middle mouse button. I think the navigation controls should be added either tutorial bar or other information page where sensible.

**Comment by triebnigg** [comment]
Describe the Cesioum controls in the FAQ

**Comment by santilland** [comment]
Added control information button in commit f011e2606ec44af0269133089e1a699757503e9b.
I think this gives a nice concise explanation of controls.
I am going to close this ticket but if there are any comments or suggestions on the controls information please comment here.
