### ISSUE TITLE
CDF file upload with filename without the .cdf file extension.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#390]
The `spacepy.pycdf ` library cannot open CDF files without the `.cdf` file extension.

The CDF file upload should check the `.cdf` file extension and add it if missing.

See the original issue https://github.com/ESA-VirES/VirES-Python-Client/issues/47 reported by @lmar76

**Comment by lmar76** [comment]
I tried also specifying a file name with `.cdf` extension but i got the same result:

```python
# Import SwarmClient (this step can be omitted if already executed in the previous examples)
from viresclient import SwarmRequest

# Create the request object
request = SwarmRequest()

# Set collection
request.set_collection('SW_OPER_MAGA_LR_1B')

# Set product
request.set_products(measurements=['F', 'B_NEC'])
                     
# Download 1 hour of data
data = request.get_between('2020-01-01T00:00:00', '2020-01-01T01:00:00')

# Save ReturnedData to a file
data.to_file('out.cdf', overwrite=True)

# Upload the file to the server to be visualized in the web client
info = du.post('out.cdf', 'test2.cdf')
```
I can see only the product previously uploaded from the web interface.

**Comment by pacesm** [comment]
@lmar76 I tried it my self and I can see the uploaded products.

I see two possible reasons why you cannot see the upload:
1) The Web client is not notified about the newly uploaded file. Try to reload the client to see if that changes.

2) Your access token was generated for a different account then you are actually using. In the logs I can see the files were uploaded by user `demo`. Are you logged in as the `demo` user?

**Comment by pacesm** [comment]
Further testing shows that the server handles CDF files without .CDF extension correctly and no change is needed.

In case of no further objection, the ticket can be closed.

**Comment by lmar76** [comment]
Tested again. t works, thank you!
