### ISSUE TITLE
IBIxTMS_2F not displayed in the time-slider

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#391]
Due to a server-side error (WPS `retrive_bubble_index` process) the periods of the elevated bubble index are not displayed in the time-slider.

Observed on v.3.1.3 production deployment.

FAO @lmar76

**Comment by pacesm** [comment]
Fixed in https://github.com/ESA-VirES/VirES-Server/commit/29127cf5e4080608c58c937dd6aed6ce47339dcb

**Comment by pacesm** [comment]
The patch has been deployed to staging.

![image](https://user-images.githubusercontent.com/4050019/74662192-b6fb7380-5199-11ea-81eb-f98e7e49ab78.png)

**Comment by lmar76** [comment]
Tested

**Comment by pacesm** [comment]
The fix has been already deployed in production on 2020-02-18.

**Comment by lmar76** [comment]
It seems there is a regression on v3.2.0 (see screenshots below of 31/12/2015 A+B).

Operational (v3.1.3):

![image](https://user-images.githubusercontent.com/20207042/76955675-e75a3d00-6912-11ea-9fa0-45b6158393f1.png)

Staging (v3.2.0):

![image](https://user-images.githubusercontent.com/20207042/76955718-f80ab300-6912-11ea-8014-57de74a73281.png)

**Comment by pacesm** [comment]
I confirm the regression. I'll take care of the fix.

**Comment by pacesm** [comment]
Fixed in https://github.com/ESA-VirES/VirES-Server/commit/0ce384087e76694437415d2ec053ac7af6f8bfd0.

The fix has been deployed on staging.

**Comment by lmar76** [comment]
Tested, it works.

**Comment by pacesm** [comment]
This issue is tracked by the [v3.2.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/8) and can be closed.
