### ISSUE TITLE
Error when trying to download TEC data in CSV format 

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#392]
Download request with following parameters:
```
Selected products:
    Alpha: SW_OPER_TECATMS_2F
    Bravo: SW_OPER_TECBTMS_2F
    Charlie: SW_OPER_TECCTMS_2F
Start time: 2016-01-01T00:00:00.000Z
End time: 2016-01-01T23:59:59.999Z
Filters: Longitude:32,35;Latitude:34,36
Output format: text/csv
```
ends with the following error 
```
Error: cannot call `vectorize` on size 0 inputs unless `otypes` is set
```

The download in CDF format passes without any error.

observed on v3.1.3 production deployment

FAO @lmar76

**Comment by pacesm** [comment]
Fixed in https://github.com/ESA-VirES/VirES-Server/commit/62e58895ba089b11c4dffc93f6421c617d6fef57

Fix is deployed on staging

**Comment by lmar76** [comment]
Tested. It works

**Comment by pacesm** [comment]
The fix has been deployed in production.
