### ISSUE TITLE
Plot label overlapping date selection widget

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#393]
1. Select: MAG_LR, EFI, IBI -> three plots are displayed in the AV
2. Collapse filters panel -> Filter panel disappears
3. Click the "calendar" button on the time slider -> date selection widget appears "behind" the plot label.

![image](https://user-images.githubusercontent.com/20207042/76949194-7ada4080-6908-11ea-8bf1-a28a33afcead.png)

![image](https://user-images.githubusercontent.com/20207042/76948742-c5a78880-6907-11ea-9581-1b36a01cf4ac.png)

**Comment by lubojr** [comment]
A fix of the calendar widget z-index has been deployed to staging.

**Comment by lmar76** [comment]
Tested, it works.

**Comment by pacesm** [comment]
This issue is tracked by the [v3.2.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/8) and can be closed.
