### ISSUE TITLE
X-axis dropdown menu "behind" time slider

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#395]
Issue detected on operational platform.

In some cases (see screenshot) the X-axis menu with the list of parameters appears "behind" the time slider and it is difficult to select the desired parameter.

<img width="873" alt="Screenshot 2020-03-30 at 16 55 44" src="https://user-images.githubusercontent.com/20207042/77927409-7bc78680-72a7-11ea-8a02-e071d663f2dd.png">

**Comment by pacesm** [comment]
The fix has been deployed to staging.
The production deployment will be fixed with the v3.2.0 release.

**Comment by lmar76** [comment]
Tested. It works, thank you.

**Comment by pacesm** [comment]
This issue is tracked by the [v3.2.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/8) and can be closed.
