### ISSUE TITLE
Can't add Sun position variables to custom product

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#396]
Issue observed on operational platform.

It is not possible to select Sun position variables in the custom product to be downloaded.

**Comment by pacesm** [comment]
Fixed in https://github.com/ESA-VirES/WebClient-Framework/commit/1d3655048441d374fdc8beea633049c3761801fd

The fix has been already deployed on staging.

**Comment by lmar76** [comment]
Tested. It works, thank you.

**Comment by pacesm** [comment]
This issue is tracked by the [v3.2.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/8) and can be closed.
