### ISSUE TITLE
Data "picking" issues

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#40]
When selecting a data point on the analytical viewer the corresponding point is shown on the globe. This does, however, not apply the other way. 

Also, when clicking on the data, a textbox pops up. It would be helpful if the corresponding point on the other "view" would be displayed on _hover_ as well.

**Comment by pacesm** [comment]
Decided not to be implemented in VirES-DEMPO-RFW-022.
