### ISSUE TITLE
AV: secondary x-axis configuration is not preserved

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#400]
When the x-axis is set to `Timestamp`, AV panel allows setting addition variable (e.g., `QDLat`) as a secondary x-axis:

![image](https://user-images.githubusercontent.com/4050019/83001518-28a25380-a00c-11ea-97fd-723c01e52f7a.png)

This secondary x-axis configuration is not preserved when re-loading the client nor saved in the exported JSON.

Observed on both production V3.2.0 and staging V3.3.0-rc.

**Comment by santilland** [comment]
Issue should be solved in latest commit 032be07b27866e57ae2fb17ad4212cd3534a8251

**Comment by pacesm** [comment]
Solved.

**Comment by pacesm** [comment]
FYI @lmar76

**Comment by pacesm** [comment]
Fix deployed on staging. Production will be fixed with the v3.4.0 release.

FYI @lmar76

**Comment by lmar76** [comment]
Tested. It works.
