### ISSUE TITLE
AV: saving of color-mapped plots is not working

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#403]
Saving of the web GUI (workspace) with color-mapped variables does not work as expected.

Workspace before export:
![screen-shot-0231](https://user-images.githubusercontent.com/4050019/85516467-82dc0780-b5fe-11ea-81b1-c1051130ffa4.png)

Workspace after import:
![screen-shot-0232](https://user-images.githubusercontent.com/4050019/85516891-fed64f80-b5fe-11ea-80cd-b8b193013f54.png)

Identified issues:
- The `diverging_1` color map is not preserved and the default `viridis` is applied instead.
- The color-map range is not preserved.
- The y-axis ranges are not preserved.

**Comment by santilland** [comment]
Colorscale should be saved now in latest commit e360c88515dc5857b1a19e2379c8e8685eb4e795
Saving of scale extent should be evaluated as for which exact cases the extent is saved, e.g. per parameter? 
How do we handle multi y axis parameters? When and how should a saved scale extent be reset?

**Comment by pacesm** [comment]
The extent is a property of the Y-axis (as it is already now, you can scroll or zoom the axis by mouse or click on the pen to change the range).
In case of two Y-axes each of them should be treated independently (as it is already now, you can scroll or zoom each axis by mouse or click on the pen to change the range).
The color-bar is just another Y-axis.

I think there are two things to consider.

First, saving of the workspace. In my opinion the workspace should be restored as saved. I.e., the saved state should contain also the extents of the Y-axes. The saving does not make sense when the plot needs to be fixed manually every time it is loaded. E.g., the plot I tried to save is using diverging color map (because the min/max range is not symmetrical the auto-scale shifts the 0) and the plots display bands of high latitudes (the auto-scale always renders the whole orbit) and it is therefore impossible to restore the plot.

Second, behavior on update (nice-to-have, not in scope of this ticket). I would be very useful to have the option to lock y-axis range and suppress the auto-scale on update. The axes would stay the same unless manually changed by the user (by mouse or entering the range manually). Since we have already GUI control for the Y-axis properties (the pencil) additional check-box or toggle-button disabling the auto-scale could be added to this control.

**Comment by pacesm** [comment]
Fix deployed on staging. Production will be fixed with the v3.4.0 release.

FYI @lmar76

**Comment by lmar76** [comment]
I repeated the test with MAGA_LR data, setting X-axis to Longitude, Y-axis to Latitude and 3rd variable to F, colorscale "jet", colour range: 10000-60000 (see screenshot):

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/20207042/94937190-8a4d5f80-04cf-11eb-9548-7c9b65a7a7da.png">

I have exported the AV settings (see [20201002T144606_vires_settings.json.zip](https://github.com/ESA-VirES/WebClient-Framework/files/5318687/20201002T144606_vires_settings.json.zip)), reset the GUI and re-imported the AV settings. The previous settings have been restored but the colour scale extent is not the one selected previously (i.e. 10000-50000):

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/20207042/94937454-e3b58e80-04cf-11eb-8f7b-f891822d26c8.png">

**Comment by pacesm** [comment]
@santilland, would it be possible to treat the color map axis the same way like the Y-axis, i.e., to store the extent in the saved JSON and allow locking of the range extent?

**Comment by pacesm** [comment]
This commit fixes the color-map extent saving: 07a9ff3e3594525cbba897671768d5507fae3ad6

The fix has been deployed on staging.

**Comment by lmar76** [comment]
It works. Thank you
