### ISSUE TITLE
NaN displayed for B_error

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#41]
B_error is a vectorial dataset providing the error in the North- , East- and Center frames. I assume that the whole vector is attempted to be read resulting in `NaN` being displayed on the analytical viewer. I believe it would have to be sepatated into 3 datasets similar to what is done to get B_N, B_E and B_C from B_NEC.

**Comment by santilland** [comment]
Separated components in commit 9b00033208efff1f500cf16af0213d12a9d4b4f5
