### ISSUE TITLE
Image export clears the AV panel

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#410]
Exporting the AV panel as an image (:floppy_disk:) leaves the AV panel blank.

Before:
![image](https://user-images.githubusercontent.com/4050019/92934649-0829c800-f448-11ea-8316-55ce374635df.png)
 
After:
![image](https://user-images.githubusercontent.com/4050019/92934826-40310b00-f448-11ea-8ff0-1bd4fb992959.png)

Redrawing forced, e.g., by window re-size or view change fixes the view. It seems like an extra refresh event triggered after the image export might solve the problem.

Observed in V3.3.0 (current production), Firefox, Safari
Seem to work correctly in Chrome.

**Comment by pacesm** [comment]
The fix has been deployed on staging.

FAO @lmar76

**Comment by lmar76** [comment]
Tested. It works.
