### ISSUE TITLE
AEBS "boundary" products not included in the list of source products

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#411]
The AEBS boundary products (i.e. AOBxFAC, AEJxPBL, and AEJxPBS) are not included in the list of source products displayed in the AV and their availability is not displayed in the tome slider (i.e. availability). E.g.:

- FAC/FAC AOB layer:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/20207042/93857327-b50f0b00-fcba-11ea-8c37-382071b42dbb.png">

- AEJ LPL/PBL

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/20207042/93857462-e2f44f80-fcba-11ea-873c-3370b3300a12.png">

- AEJ LPS/PBS

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/20207042/93857499-f4d5f280-fcba-11ea-87c4-d3f4fab2bdae.png">

**Comment by pacesm** [comment]
The fix has been deployed on testing.

**Comment by lmar76** [comment]
Tested. I forgot to mention that the "boundary" product is not even visible on the time slider. Do I have to create a separate issue?

**Comment by pacesm** [comment]
If you think this is an issue then I prefer to track it in a separate ticket. Thanks.
