### ISSUE TITLE
Problem loading LPL & MAG residuals together

### ISSUE THREAD

**Issue by smithara** [ESA-VirES/WebClient-Framework#412]
Detected on https://staging.vires.services/

What I tried:
1. Enable `Auroral Electrojet - LC`
2. Enable `Magnetic data`
3. Enable `Magnetic Model`
4. Change Mag data settings to display `Residuals to Model`

![image](https://user-images.githubusercontent.com/6398449/94124064-79a44600-fe4c-11ea-8d0c-36c45086df9c.png)

The `LPL` line disappears (though boundaries remain) and the loading widget is stuck on. Same thing happens with the `LPS`.
However, if I export the workspace and then import it, then it displays correctly
[20200924T084028_vires_settings.zip](https://github.com/ESA-VirES/WebClient-Framework/files/5274727/20200924T084028_vires_settings.zip)

![image](https://user-images.githubusercontent.com/6398449/94124480-f9321500-fe4c-11ea-915b-39b33f27e328.png)
(this is interesting to show because it gives some indication that the electric currents (LPL) are derived from the magnetic disturbances)

**Comment by pacesm** [comment]
This regression is not specific to MAG/LPL combination.

**Comment by pacesm** [comment]
The fix has been deployed to staging.

![image](https://user-images.githubusercontent.com/4050019/94458253-fc633300-01b5-11eb-8ee4-a1fd4e537d9f.png)

**Comment by lmar76** [comment]
Tested.

**Comment by smithara** [comment]
Looks good!
