### ISSUE TITLE
Re-loaded client does not display model residuals.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#413]
When the magnetic residual are displayed on the globe

![image](https://user-images.githubusercontent.com/4050019/94464033-2ae50c00-01be-11eb-88ef-b15b280f75a4.png)

and the client is reloaded the display falls back to the scalar magnetic intensity

![image](https://user-images.githubusercontent.com/4050019/94464203-74cdf200-01be-11eb-81ab-ae7d4531c6a7.png)

even when the stored client state includes the proper information about the displayed parameter.

This happens also when the workspace is exported to a JSON file and imported back.

Observed on current the production deployment v3.3.0.

FAO @lmar76

**Comment by pacesm** [comment]
The fix has been deployed on staging.

The production will be fixed with the upcoming V3.4.0 release.

**Comment by lmar76** [comment]
Tested.

**Comment by smithara** [comment]
Looks good! @pacesm you can close this
