### ISSUE TITLE
AEBS: set the default LPL and LPS height to 110km

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#414]
The default LPL/PBL and LPS/PBS default height should be 110km for both products.
Right now LPS/PBS is displayed 110km above ground and LPL/PBL 450km.

**Comment by lmar76** [comment]
Is it possible to test it? This parameter is not visible in the GUI.

**Comment by pacesm** [comment]
It is just a visualization parameter and you can test it only visually. Long story short, the display should like
![image](https://user-images.githubusercontent.com/4050019/94662459-b5398700-0308-11eb-928b-e8644aaba7e7.png)
instead of
![image](https://user-images.githubusercontent.com/4050019/94662657-fe89d680-0308-11eb-9299-d2d5b81ad29d.png)

When you show LPS and LPL at the same time an offset has to be added to the height to prevent the features to overlap and become indistinguishable. Therefore, in that case, the display will not look much different than right now.

For sake of completeness, I enclose the saved zipped view [LPL_height_test.zip](https://github.com/ESA-VirES/WebClient-Framework/files/5304306/LPL_height_test.zip)

**Comment by pacesm** [comment]
The fix has been deployed on staging.

**Comment by lmar76** [comment]
Tested. It works.
