### ISSUE TITLE
AEBS "boundary" products not displayed on the time slider

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#416]
The AEBS "boundary" products (product name and temporal availability) are not displayed on the time slider.

- Auroral Electrojets - LC: only LPL product is displayed:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/20207042/94545965-87dbd300-024d-11eb-9c84-35bc36a7b813.png">

- Auroral Electrojects -  SECS: only LPS product is displayed:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/20207042/94545761-4519fb00-024d-11eb-9b1b-89bdea2b0dfc.png">

- Electric current data: only FACxTMS_2F is displayed:

<img width="899" alt="image" src="https://user-images.githubusercontent.com/20207042/94546109-bbb6f880-024d-11eb-9c09-78ae0370d62e.png">

**Comment by pacesm** [comment]
@lmar76 I looked at this issue and the implementation is actually trickier than it might seem.
Apart from the display of the second product, we need to also solve clipping of the time extent of the yearly boundary product so that product id is displayed within the current time window.

I propose we defer implementation of this feature after V3.4.0 release.

**Comment by lmar76** [comment]
@pacesm ok

**Comment by santilland** [comment]
An implementation was introduced for this and deployed on staging. When activating a LPL or LPS product the availability of the corresponding PBL and PBS products will be shown in the timeline in the same color as the product.

**Comment by pacesm** [comment]
The boundary products are now shown also for the FAC_AOB products. I consider the ticket resolved.

@lmar76 Please check whether we can close the ticket.

**Comment by lmar76** [comment]
Tested. Please, close the ticket.
