### ISSUE TITLE
Timestamp as NaN in y-axis

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#42]
`timestamp` works fine in the x-axis.

But, similar to #41, when `timestamp` is displayed in the y-axis on the analytical viewer, it is displayed as NaN.

**Comment by santilland** [comment]
Solved issue in domain and scale adaptation for y Axis; Time values are represented correctly again. Introduced in commit 9b00033208efff1f500cf16af0213d12a9d4b4f5
