### ISSUE TITLE
Save scatterplot to image - downloaded file without extension

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#420]
I tried to save a scatterplot as an image:

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/20207042/94938304-f381a280-04d0-11eb-9c9b-46ffc943964c.png">

After clicking the OK button, the file is downloaded but it does not contain the extension, i.e.: VirES_for_Swarm_20201002 instead of VirES_for_Swarm_20201002.png. The same issue occurs selecting jpeg format.

I have repeated the test with Chrome (instead of Firefox) and the issue is not observed.

**Comment by santilland** [comment]
Solved in commit 5c2f5b64cc018491c3fd19b14593efe79ee82909
Deployed to staging

**Comment by lmar76** [comment]
Tested. It works. Thank you!
