### ISSUE TITLE
Add tooltips to axis controls in the AV (enhancement)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#422]
There are two buttons near the axis in the AV (see screenshot below). The usage of "pencil" is straightforward but the usage of "lock" is not. Could it be possible to add tooltips on the buttons briefly explaining their usage?

<img width="360" alt="Screenshot 2020-10-06 at 11 40 06" src="https://user-images.githubusercontent.com/20207042/95185302-d1d23500-07c8-11eb-8753-c6b3a0f61236.png">

**Comment by pacesm** [comment]
The purpose of the lock is to "lock" the range to the current extent and keep it fixed even when a different time selection is made.

We can look into this and see if a tool tip can be easily added.

**Comment by pacesm** [comment]
Tooltips were added to the AV panel (0f27ecadde633c599a72a9a1bf28152137049f56)

![image](https://user-images.githubusercontent.com/4050019/102918920-2d3ac780-4488-11eb-81eb-686df8bc1a52.png)

Deployed on staging.

**Comment by pacesm** [comment]
@lmar76,  could you please check the feature so that we can close the ticket? Thanks.

**Comment by lmar76** [comment]
Tested. Please, close the ticket.
