### ISSUE TITLE
Kp, Dst, dDst, F10 indices not available for filtering in the Download panel

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#423]
It is possible to select Kp, Dst, dDst, F10 values for filtering data to be downloaded by selecting their values in the AV's filtering panel and clicking the Download button (see screenshot).

<img width="766" alt="Screenshot 2020-10-06 at 11 49 13" src="https://user-images.githubusercontent.com/20207042/95186765-a0f2ff80-07ca-11eb-8ccf-7b690c0eccc8.png">

Howevere, it is not possible to select these parameters through the "Add filter" button (see screenshot).

<img width="766" alt="Screenshot 2020-10-06 at 11 49 37" src="https://user-images.githubusercontent.com/20207042/95186465-4fe30b80-07ca-11eb-835a-fe2a9e461e54.png">

**Comment by pacesm** [comment]
The fix has been deployed on staging.

**Comment by lmar76** [comment]
It works. Thank you
