### ISSUE TITLE
Cannot save whole image when view = Analytics

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#43]
When saving an image of the analytics viewer from the split-screen view, the whole image is saved.

If one saves the same image when in the full-screen analytics view, the image is cropped on the right hand side.

![analytics-1](https://cloud.githubusercontent.com/assets/17086561/14453576/f8b3a5f8-0095-11e6-8be4-ff9dd2d6fe31.png)

**Comment by santilland** [comment]
Updated image creation; It was not taking into consideration the change in size. Solved in commit 9b00033208efff1f500cf16af0213d12a9d4b4f5
