### ISSUE TITLE
AV: colormaps displays NaN values

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#432]
The 3rd variable color-mapping in the AV 2D plots maps NaN values to the lower bound of the color range:

![image](https://user-images.githubusercontent.com/4050019/103218028-432e0980-491a-11eb-9c50-269cd7f082cd.png)

This is incorrect and misleading. Nothing (or fully transparent point) should be displayed for the mapped NaN values.

Saved workspace: [colormap_with_NaN_values.json.gz](https://github.com/ESA-VirES/WebClient-Framework/files/5747496/colormap_with_NaN_values.json.gz)

**Comment by santilland** [comment]
Added check for NaN when calculating color, solved in staging
