### ISSUE TITLE
AV: refine the overaly symbols to allow seeing the data. 

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#436]
AEBS team responded to the overlay symbols:

> The tools for line plots are nice, as they generate the legends 
> explaining the different symbols. However, the format of the legends
> is somewhat too spacious as they seem to hide the actual data in some
> cases (see attached example).  Perhaps the frames could be somehow
> tighter?

FAO @lmar76

**Comment by pacesm** [comment]
The overlays symbols can now be disabled in order to see the data  below them by clicking on the legend label.

![image](https://user-images.githubusercontent.com/4050019/110144287-74263100-7dd8-11eb-9973-fc62ba715cd8.png)

implemented in e3e56e0a9c32bc5bfbc329a8ad6092f81f549b7d

deployed on staging

**Comment by lmar76** [comment]
Tested. Overlay symbols are displayed only for variable:
- FAC (FAC/FAC AOB)
- J_QD (AEJ LPL/PBL)
- J_DF_SemiQD (AEJ LPS/PBS)

**Comment by pacesm** [comment]
Solved. Tracked by the 3.5 milestone.
