### ISSUE TITLE
Plot orbits with different colors.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#437]
PRISM team responded to the orbit plotting:
> ... Different colours for the three satellite orbits would be an improvement.

**Comment by pacesm** [comment]
Already implemented and deployed on staging

![image](https://user-images.githubusercontent.com/4050019/108222345-ffe16180-7138-11eb-9f83-a85e881e552d.png)

**Comment by pacesm** [comment]
FAO @lmar76

**Comment by lmar76** [comment]
Tested

**Comment by pacesm** [comment]
Solved. Tracked in the 3.5 milestone.
