### ISSUE TITLE
Misaligned "Add filter" button

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#442]
The "Add filter" button in the Download Manager UI is misaligned:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/20207042/113115262-8b581300-920c-11eb-9c79-6d2656076358.png">

**Comment by pacesm** [comment]
I can confirm the misaligned "Add filter" button in the current stable Chrome 89.0.4389.114.
This seems like a browser-specific issue.

**Comment by lmar76** [comment]
It happens also with Firefox 84.0.2

<img width="790" alt="image" src="https://user-images.githubusercontent.com/20207042/113271584-fa9c3880-92da-11eb-8ae8-833433a07eb1.png">

**Comment by pacesm** [comment]
Interesting. I looks okay in in my Firefox 87.0

![image](https://user-images.githubusercontent.com/4050019/113272548-063c2f00-92dc-11eb-9b63-61994a4b3997.png)

In addition, the same glitch has been observed on the production instance. This does not seem like a V3.5 regression.
Nevertheless, it should be investigated and fixed. Hopefully, this will required just a simple CSS layout adjustment.

**Comment by pacesm** [comment]
The misaligned button is cased by the negative margin: https://github.com/ESA-VirES/WebClient-Framework/blob/ecf9f3f9476772a6945cfe2f515fd09f958ea58f/app/styles/download.scss#L132 trying to compensate for the broken layout of the `w2ui-field` list. The offset is apparently interpreted differently in different browsers (reps. browser versions) and this "trick" is not working.

**Comment by santilland** [comment]
Issue should be solved with e09e62411a7a37f341672cc766bb99b49e9ca9f3
Update was deployed on staging.

**Comment by lmar76** [comment]
Tested.
