### ISSUE TITLE
Truncated download time-stamps.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#443]
The time-stamps in the download panel are truncated right after the hour "2021-03-31T07:"

![image](https://user-images.githubusercontent.com/4050019/113271473-dcced380-92da-11eb-85d4-8633b1e024d2.png)

This has been observed in Chrome and Firefox and does not seems to be browser specific.

FAO: @lmar76

**Comment by pacesm** [comment]
Fixed. Deployed on staging.

**Comment by lmar76** [comment]
Tested. It works
