### ISSUE TITLE
Handling of multiple parameters and overplotting in graphs

### ISSUE THREAD

**Issue by santilland** [ESA-VirES/WebClient-Framework#46]
As of now the plot generation displays the maximum domain of all selected parameters for the y Axis. It could be of significant interest to create separate "domains" or axis if the domains of the selected parameters is very different.
Here we can discuss some possible approaches for this idea.

**Comment by pacesm** [comment]
@santilland Is this still relevant with the multiple plots sharing the same x-axis?

**Comment by santilland** [comment]
I would say the multiple plots is a solution to the described problem so i think this can be closed.
