### ISSUE TITLE
Edits in "About" Page

### ISSUE THREAD

**Issue by triebnigg** [ESA-VirES/WebClient-Framework#47]
under section "The Data",

* bullet related to CHAOS-5: 

 * replace hyperlink so that it points to the DTU page which includes information about the Version 4 of the Model: http://www.spacecenter.dk/files/magnetic-models/CHAOS-5/

 * change text in brackets so that it reads "....  with ground observatory data (CHAOS-5x_v4)"

* bullet related to Kp Index, make sentence look like follows:
"The disturbances in the horizontal component of the Earth's magnetic field (planetary Kp Index)"

**Comment by santilland** [comment]
Changes introduced in commit a9fc5618de01102410051a22efe05c9d78ca6d2b (not yet deployed) marking this as closed, if any other changes required feel free to add them here.
