### ISSUE TITLE
Sign-up page additions

### ISSUE THREAD

**Issue by triebnigg** [ESA-VirES/WebClient-Framework#48]
At the bottom of the page there shall be two tick-boxes:

1. **not ticked**: I have read and accept the [Terms and Conditions for the Utilisation of ESA’s Earth Observation Data](~/accounts/tos).

2. **already ticked**: I am interested in receiving updates and news related to VirES for Swarm.

Explanation to 1.: We have two terms, the "ESA Data TC" and the "EOX VirES ToS", only the "ESA Data TC" need to be eplicitly accepted by the user by ticking-off this box.

**Comment by santilland** [comment]
This has been discusses and implemented as agreed: Being one tickbox describing to have read and agree to both terms.
"I read and accept the ESA Data Terms and the VirES Service Terms *"

If this changes for some reason please feel free to comment on this ticket.
