### ISSUE TITLE
Mixed content in new landing page

### ISSUE THREAD

**Issue by Schpidi** [ESA-VirES/WebClient-Framework#49]
On the new landing page I get this error: `Mixed Content: The page at 'https://vires.services/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:400,700,600'.`

**Comment by santilland** [comment]
Changed template to use https protocol for font retrieval in commit https://github.com/ESA-VirES/VirES-Server/commit/f0e2c2f5035b25344d6db0f606a6899973d2d3cb

I will close this issue as the error should not be appearing any longer. If any issues persists, please feel free to comment it here.
