### ISSUE TITLE
Disable GetFeatureInfo queries for the magnetic model WMS layers.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#51]
A click on the Cesium 3D globe when a magnetic model layer is displayed trigger 3 WMS `GetFeatureInfo` requests (each with different mime-type).

The VirES-Server WMS implementation does not provide this operation and the `GetFatureInfo` requests always fail.

Please, disable the WMS `GetFatureInfo` in the Cesium 3D globe widget.

**Comment by santilland** [comment]
GetFeatureInfo disabled for WebMapImagery Providers in commit 0d4360e5e42bf6c96e23731b9524a2d54fe20974.
Marking it as closed.
If there is still any issue feel free to comment here.
