### ISSUE TITLE
Kp & Dst index layer settings are broken.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#53]
Kp & Dst index layer settings widgets are broken. Need to be fixed or better removed as there is nothing to be set for these layers anyway.

**Comment by santilland** [comment]
Removed setting panel for Indices as they have no purpose. Done in commit f14852c293ea003f848de1db4c89fbc73b86ebdc.
Marking it as closed.
If there is still any issue feel free to comment here.
