### ISSUE TITLE
Error in updated WPS Process for custom model (maybe others too) 

### ISSUE THREAD

**Issue by santilland** [ESA-VirES/WebClient-Framework#55]
When uploading SIFM (shc file) to custom model with preset settings the returned image looks like this now:
![download](https://cloud.githubusercontent.com/assets/4036819/14635983/23510b5a-0629-11e6-91ce-1daa826f9b3d.gif)

Previously it looked like this:
![download 1](https://cloud.githubusercontent.com/assets/4036819/14635989/2ecdc194-0629-11e6-9816-b631d63dc200.gif)

It seems there are issues with the coefficient range

**Comment by pacesm** [comment]
solved by https://github.com/ESA-VirES/VirES-Server/commit/72965447e74c947750662c62e3840b1fb966edf5
