### ISSUE TITLE
Strange output when viewing MAGC

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#58]
When viewing magnetic intensity data from Charlie, there seems to be two lines, where one with value zero. 
![image](https://cloud.githubusercontent.com/assets/17086561/14736296/877be9b6-0876-11e6-9867-529bcbbf7d9d.png)

**Comment by santilland** [comment]
The Absolute Scalar Magnetometer from Charlie has some issues as far as i know. Maybe some kind of buildup or something where it is activated/deactivated to assure accurate measurements so there are quite a lot of 0 values, so i would say this is correct output. If there is desire to handle the Charlie issues differently this needs to be discussed.

**Comment by pacesm** [comment]
@miktoki: We do not change the measurement values. The anomalies, you are referring to, come directly from the SWARM products.
As Daniel pointed out, the question is how to interpret and display these (presumably invalid) measurements. In addition, however, we should also check the SWARM product specification whether there is not a quality flag which can be used to exclude these values.

**Comment by miktoki** [comment]
You are right, it is straight from the data.

**Comment by miktoki** [comment]
Nonetheless, it does display something(as can be seen from the above image).  Is it displaying the "true" product value of F from the ASM(ie. 0) and the value F using the absolute value of VFM measurements?

**Comment by santilland** [comment]
Yes you are right, we spotted a little error in the registration of the data on the staging server. Seems during some testing we linked some Bravo products to the Charlie collection so you are seeing information of both Bravo and Charlie, that is why it looks like that. We are working on solving the issue.

**Comment by eox-cs1** [comment]
Swarm Products registered on Staging have been corrected.

**Comment by pacesm** [comment]
I checked the `staging` instance and all the product are in the right collections.
The issue has been resolved.
