### ISSUE TITLE
Download data filtered with kp or dst

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#59]
when attempting to download any mag data filtered using the Kp-index or dst, I get the following message:

"Error Downloading Data! This might be caused by too many records being selected. Please refine your filter criteria. Should this issue persist, please, check the browser log."

Browser log indicates bad request(400) on post.

**Comment by pacesm** [comment]
Apart from the server-side bug the issue is related to https://github.com/ESA-VirES/WebClient-Framework/issues/23.

**Comment by pacesm** [comment]
The server-side bug has been fixed and the patch deployed.
