### ISSUE TITLE
Time slider problem using Internet Explorer 11

### ISSUE THREAD

**Issue by triebnigg** [ESA-VirES/WebClient-Framework#6]
**Testing still with VirES prototype**: Timeslider is partially insensitive to selections. Although it shows productnames/tooltips on mouseover, it does not take input for selection of period of interset.

**Comment by santilland** [comment]
There was an issue of how events are handled in Internet Explorer, the event object could not be created. A possible solution is described here:
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill
This was introduced to the timeslider library and seems to be working. Integrated in Webclient in commit d9044807fbea00e90bda4c84dcd99764b0a45bf0
