### ISSUE TITLE
Landing page video - end behaviour

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#60]
At the end of the demo video, other videos are suggested to you - as is normal for youtube videos. Is it possible to eg. rewind the video instead? Alternatively, since we are targeting the newest browsers, one could use the html5 native `video`?

**Comment by santilland** [comment]
There is the possibility to remove related videos in embedded sources, needed to add rel=0 at end of embed url. Done in commit https://github.com/ESA-VirES/VirES-Server/commit/5e4ae4816afa018be916b27030de46a18951beb4 
This will put the video paused from the beginning after playback.
I think this behavior is as expected and will close the ticket, for an other further questions or requests feel free to comment.
