### ISSUE TITLE
CDF attributes not stored on download

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#61]
When comparing original swarm products with swarm products downloaded from VirES I found that the attributes of the original are not stored in the product as shown below:

    >>>vires_product = spacepy.pycdf.CDF("SW_OPER_MAGA_LR_1B_20160221T000000_20160221T235959_MDR_MAG_Filtered.cdf")
    >>>orig_product = spacepy.pycdf.CDF("SW_OPER_MAGA_LR_1B_20160221T000000_20160221T235959_0408_MDR_MAG_LR.cdf")
    >>>orig_product.attrs
    <gAttrList:
    CREATOR: CDF converter Tool 1.0 (GMV AD) [CDF_CHAR]
    ORIGINAL_PRODUCT_NAME:   SW_OPER_MAGA_LR_1B_20160221T000000_20160221T235959_0408 [CDF_CHAR]
    TITLE: SW_OPER_MAGA_LR_1B_20160221T000000_20160221T235959_0408_MDR_MAG_LR [CDF_CHAR]
    q_STR_VFM: [-0.01323794  0.61888483  0.02264587  0.78504362] [CDF_DOUBLE]
    r_CoG_VFM: [ 0.  0.  0.] [CDF_DOUBLE]
    >

    >>>vires_product.attrs
    <gAttrList:
    
    >

    >>>orig_product['F'].attrs
    <zAttrList:
    DESCRIPTION: Magnetic field intensity [CDF_CHAR]
    UNITS: nT [CDF_CHAR]
    >

**Comment by pacesm** [comment]
@miktoki: You are right. When we create the CDF output we do not currently copy the attributes from the original CDF files (note that the filtered result may be composed from multiple source products).

**Comment by miktoki** [comment]
@pacesm would it maybe be possible to append each CDF input filename to `ORIGINAL_PRODUCT_NAME. Either way, the product parameter attributes (eg. attributes of `F`) should not be affected by having composite products

**Comment by pacesm** [comment]
@miktoki You are right, the attributes of the variables are the same for all products and they can be simply copied.

Regarding the original product names, I see no technical problem to append the names of all source products.

**Comment by pacesm** [comment]
resolved https://github.com/ESA-VirES/VirES-Server/pull/23

The following global attributes are added to the produced CDF:
  - `CREATOR` - creator SW info
  - `CREATED` - creation time-stamp
  - `DATA_FILTERS`  - list of applied data filters
  - `DATA_TIMESPAN` - time selection
  - `ORIGINAL_PRODUCT_NAMES` - list of the filtered SWARM products

The attributes of the variables are copied from the source SWARM products. Each variable has now these attributes:
  - `DESCRIPTION`
  - `UNITS`
