### ISSUE TITLE
Layers coastline + streets

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#62]
"Coastline" emphasizes the coastline as expected. "Streets", however, while it does display streets once you zoom sufficiently in, what is the more useful part of it (political boundaries, country+ city labels etc) is not so obviously a part of "Streets" based on the name. Would it be possible to rename it accordingly (eg "Political" layer)?

In addition, "Coastline" is already a subset of "Streets". Would it be possible to factor the coastline out of "Streets"?

**Comment by triebnigg** [comment]
for V1.0:
- Streets" will be replaced by "Borders  and Labels"

**Comment by santilland** [comment]
Moved possible discussion of overlay layer design to issue #75.
Renaming of layer done in commit 8d0b48b07b2d1c13780a9192638156ae57840398
I will close this ticket, further discussion can be done in the previously stated ticket.
