### ISSUE TITLE
Strange behavour of dst and kp after going out of range

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#65]
dst and kp indices are not as up to date as the swarm products (which on a sidenote does not make so much sense to me as they update their dataset every 3 hours, and swarm updates it correspondingly). When looking at an area where there are swarm products but not these indices, the filters turn to NaN. When one afterwards tries to go back to an area where these exist - the filters(dst + kp) are corrupted displaying strange things. 

Presumably this is due to a `transform` from `NaN`.

**Comment by pacesm** [comment]
Well, let's decompose this one to the principal issues ...

First, we have to check why the indices have not been updated over the recent days. The automatic updates is responsibility of @eox-cs1 I expect him to report on this when he comes back to the office tomorrow.

Second, the server fetches `NaN` values when there are Kp and Dst values available for the selected measurements and it is the expected correct behaviour.

Third, the client should handle the missing values gracefully and the filters should display only valid number ranges (i.e., no `NaN`).

**Comment by eox-cs1** [comment]
#65 As based on an internal discussion/agreement the staging version (since it is mainly intended to evaluate new features) does not receive automated data updates. This is also true for the Auxiliary datasets.
When I fixed the cross-registerred products last week, I wasn't aware about the need to have the Auxilliary data in sync with the Swarm products. Sorry for that. 
I updated the Auxillary data as of today (20160428) and also registerred the latest available swarm data (until 20160424) to staging.  
I hope this fixes the above problem.

**Comment by miktoki** [comment]
@pacesm I'll leave it to you to determine if the principle issues are resolved

**Comment by pacesm** [comment]
@miktoki: I think we can live with the manual synchronisation of the staging instance right now.

It it important, that the automatic updates shall be ready on the production system which will be open to public and used for the acceptance review.

The client `NaN` filtering issue is still open.

**Comment by santilland** [comment]
The client does handle gracefully the NaN values since latest Analytics Viewer release integrated in commit f89fc4571d0724205a2a721e2708044c62970a05. From my point of view all in all we can close this ticket now.

**Comment by santilland** [comment]
Ok, i am closing this ticket now to have an overview of what has been done and what not. If there is still any uncertainty or desired changes please comment here, we can reopen the ticket at any time.
