### ISSUE TITLE
IE Missing label for filters

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#67]
Filter labels are not displayed on IE.

![noname2](https://cloud.githubusercontent.com/assets/17086561/14859515/bf32b718-0ca4-11e6-89ee-587dfc0159f8.jpg)

**Comment by santilland** [comment]
Issue related to #68 Internet explorer does for some reason not support [innerHTML](https://support.microsoft.com/en-us/kb/276228). Updated analytics viewer in commit f89fc4571d0724205a2a721e2708044c62970a05. The update in analytics viewer makes use of (innerSVG polyfill)[https://code.google.com/archive/p/innersvg/] to solve the issue.
This was tested on internet explorer 11 and edge and seems to solve the issue. If there seems to be any other problems related to this feel free to comment, closing the ticket.
