### ISSUE TITLE
IE save analytical viewer image

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#68]
When attempting to save an image from analytical viewer using IE no image is saved. 
Console output:

Error

    SCRIPT5007: Unable to get property 'documentElement' of undefined of null reference
    File: av.min.js, Line: 3, Column: 8054

**Comment by santilland** [comment]
Saving the image makes use of innerHTML which was not working in IE. Same solution as for issue #67, described there.
Closing this issue, tested it on IE 11 and Edge. If the issue persists for any reason please comment here.
