### ISSUE TITLE
Landing page image[Priority:medium]

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#73]
spreadsheet table is shown on first image on landing page. It was suggested changed to an analytic viewer image.

**Comment by santilland** [comment]
Updated banner with analytics view. Pushed in commit https://github.com/ESA-VirES/VirES-Server/commit/a64feafa9ca48ab1753b2ee5eba359265632f181 and available on staging.
Marking this ticket as closed, if new there is any comment on the new image please comment it here and possible changes can always be discussed.
