### ISSUE TITLE
Change default zoom level on timebar

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#74]
Increase initial zoom level on entering VirES so it is easier to move the time range instead of increasing its size.

**Comment by santilland** [comment]
Increased initial zoom level in commit ce266c5d183c453ce0a508c560750a7ce87763f3, also made selection a little more visible reducing alpha. If this is acceptable i would close this ticket, please let me know.

**Comment by santilland** [comment]
I will close this ticket now, please feel free to comment is there is any other feedback.
