### ISSUE TITLE
Possible updates to overlay layers

### ISSUE THREAD

**Issue by santilland** [ESA-VirES/WebClient-Framework#75]
The "Coastline" layer is already a subset of "Streets". Removing this information from "Streets" could be considered. Other ideas can be discussed here.

**Comment by Schpidi** [comment]
Not sure which layer from EOX::Maps you're using but `overlay_base` does not include coastlines compared to `overlay`.

**Comment by Schpidi** [comment]
In addition it has nice curved labels...

**Comment by santilland** [comment]
Updated client to make use of overlay_base instad of overlay, for the layer now called "Borders and Lables" which now does not include coastlines any more.

**Comment by santilland** [comment]
After analysis and looking at many publications related to magnetic data we have come to the conclusion that a simplified overlay with coastlines in black and additional (lighter) country borders is best suited. Additional graticule layers for geographic and geomagnetic longitude latitude provide necessary context information on the globe.
This layers are introduced in service version 1.2, so i will be closing this ticket. If there is any other feedback to the discussion please feel free to comment.
