### ISSUE TITLE
Colours in analytics viewer

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#79]
It has been pointed out by several people who tested it that at times it was difficult to see colour of a dataset in 2 cases:
1. Same Satellite - multiple datasets + many datapoints: The border/contour/edge colour can in this case overshadow the value of the points, so that all points have the same colour (eg. blue for Swarm Alpha). Could it in this case be worth considering not having the edge colour as it adds no information?
2. Several Satellites - same dataset: In this case the edge colour is important - but may be difficult to see - resulting in it being difficult to see difference between the satellites. Could it be worth using stronger colours?

**Comment by santilland** [comment]
As of service version 1.1 the color use was simplified, now single colors are used for each different parameter/satellite combination, as can be seen in the image below.
![image](https://cloud.githubusercontent.com/assets/4036819/21315296/c75e7b46-c5fb-11e6-9a56-55c2e6f7a3fd.png)
This increases the readability of the plot considerably. I will close the ticket, if the current solution does not seem acceptable, please comment and we can reopen the ticket for further discussion.
