### ISSUE TITLE
Provide support email adress

### ISSUE THREAD

**Issue by triebnigg** [ESA-VirES/WebClient-Framework#8]
On https://testing.vires.services/eoxs/accounts/confirm-email/#_=_

The sentence "Please contact us if you do not receive it within a few minutes" should be augmented to "Please contact us under **support@vires.services** if you do not receive it within a few minutes"

**Comment by pacesm** [comment]
The  **support@vires.services** address has been created. The templates still need to be updated.

**Comment by santilland** [comment]
Added in commit:
https://github.com/ESA-VirES/VirES-Server/commit/76d795c9f751900948b72db4a4a459fe0439991c
