### ISSUE TITLE
Tutorial update

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#81]
The tutorial needs to be reviewed ensure it being up-to-date.

Some errors I found:
1. In "Geomagnetic field models - settings" it refers to the cogs icon for settings,
2. In Field lines it refers to the tools widget
3. In Field lines it refers to the Area button icon - which has been replaced by a button with text

**Comment by santilland** [comment]
Tutorial updated in commit 7adc8f77aeeb6604772083fc03c1694212468e31
* Changed cogs to sliders icon
* Removed reference to tools widget and area button changing it to following text:
Field lines can be visualized for a selected area on the virtual globe. We already created a selection to display them. A selection can be done by activating the "Select Area" button located on the top right of the map view.
If a selection is already active, the button will clear the slection first containing the text "Clear Selection".

Marking this as closed, if new text needs any changes or there is still any other update to be done just comment on the ticket and it will be reopened,
