### ISSUE TITLE
Rephrase on landing page [Priority:medium]

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#82]
Re-phrasing of the first sentence with the following has been suggested: "VirES for Swarm is a highly interactive data manipulation and retrieval interface for the ESA Swarm constellation mission magnetic products. It includes tools for studying various Earth magnetic models by comparing them to the Swarm satellite measurements at given solar activity levels."

In the Features secion, first sentence: "Here is a demonstration of the VirES for Swarm main features available for users" (available for users unnecessary?)

From the sign-up part, remove the statement: "(no need to remember new passwords!)"

**Comment by santilland** [comment]
Rephrase done in commit https://github.com/ESA-VirES/VirES-Server/commit/851dbecd0d8104308814e5c753c5e551e94584dc
* First sentence as described
* Could not find the "available for users" sentence, maybe it was removed at an earlier point already
* no need to remember a new password removed
Closing the ticket as changes have been done, any further change requests or feedback can be added as comment at any point.
