### ISSUE TITLE
Center on signup [Priority: low]

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#83]
On small (wide?) displays when clicking on signup one is not able to see the signup text, only the image above. Would it be possible to link to the title?

**Comment by santilland** [comment]
Changed position of signup link below the image in commit 851dbecd0d8104308814e5c753c5e551e94584dc
This solves the problem with small displays, closing the ticket. Feel free to comment here if there is any feedback related to this.
