### ISSUE TITLE
Kp to categorical

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#85]
The kp - data has values of 00,03,07,10,13,17,20,23 ...  corresponding to the actual kp -values used by the community: 0,0+,1-,1,1+,2-,2,2+ ... 
Would it be possible to change the Kp ticks to reflect this?

**Comment by pacesm** [comment]
related to https://github.com/ESA-VirES/WebClient-Framework/issues/312

The *Kp* are now displayed as decimals between 0 and 9.
