### ISSUE TITLE
AM/PM to 24h

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#86]
Currently viewing timestamps of less than a day shows 12-hour clock times. 24-hour times are more commonly used in scientific applications and are less ambiguous. It has therefore been suggested to change this.

**Comment by santilland** [comment]
Updated analytics viewer and timeslider to work and display UTC times which also now uses 24h formatting in commit ff66d12b35bc4e0359abd025dffb31d92961c0a3. 

Closing the ticket, if there is still any comments or feedback as always feel free to comment.
