### ISSUE TITLE
Simplify analytic viewer legend

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#87]
Analytic viewer legend currently is on the form `SW_OPER_MAGX_LR_1B - Y` With X being the satellite and Y being the parameter. It has been pointed out that a lot of this is unecessary. Currently only X and Y are strictly speaking necessary.

**Comment by santilland** [comment]
Since service version 1.1 and the introduction of merged products a simplified label has been introduced to the analytics viewer where satellite and parameter is shown, e.g. "Alpha - F".
Closing the ticket, if there is any other feedback or need for discussion please comment.
