### ISSUE TITLE
No units in analytical viewer

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#88]
There are no units displayed along the y-axes. One common way to do this is to display this in brackets after the parameter name eg. `F[nt]`.

**Comment by santilland** [comment]
Unit were integrated in latest staging deployment, the current nomenclature used is e.g. F(nT).
Is the use of square brackets more common?

**Comment by miktoki** [comment]
There are three prevalent ways of indicating units: 
 
- parantheses: very widespread use esp. in non-technical papers, but can be confused for function input "f(x)" when x can be different things, eg. F(t), F(r), F(lat) etc.
- square brackets, used to avoid the problem with normal parantheses
- division by unit. Make what you are plotting unitless and at the same time implicitly stating the unit eg "F/nt". This is compact, but may be unnatural to some, and confusing if combined with other mathematical expressions

Personally, I find the square brackets to be the least ambiguous. When looking at a small sample of the litterature in geoscience both parantheses seems to be a bit more common than square brackets(division is not common), but Nils Olsen(if he is any indication of convention in geomagnetism) seems to stick to square brackets.

**Comment by santilland** [comment]
Since release of service 1.1 square brackets have been used and no negative feedback has been received  related to this, so i will be closing this ticket. If at some point there is the need we can reopen this discussion.
