### ISSUE TITLE
Cesium different globe size after switching back & forth

### ISSUE THREAD

**Issue by triebnigg** [ESA-VirES/WebClient-Framework#9]
1. starting in 3D with the full globe in view (starting size of globe); 
2. switching to 2D (or 2.5D) view (no additional interaction); 
3. switching back to 3D results in globe about tripple size of the starting globe (requiring the user to zoom out in order to get back to starting size)
--> return to starting size would be good.

**Comment by santilland** [comment]
In the new Cesium release switching of views has been greatly improved. New version was introduced in commit 926497bb8fbd31dafdf40495ce4e5cc226d51216
In any case changes in this behavior means changing core functionality of cesium, if this is considered an issue it should be adressed in the cesium forum. I am closing this ticket as i consider it solved now, if there is any question or followup feel free to comment and we can reopen the ticket.
