### ISSUE TITLE
Analytic viewer zoom 1 axis

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#90]
Currently when zooming in the analytical view it zooms along both axes. As features are on very different scales it is useful to be able to zoom along one axis (eg. by scrolling on the relevant axis).

This problem is very evident when selecting two datasets with very different scales. It becomes difficult to swich between viewing both of them and only one.

On side note, I think the max zoom level for the analytic viewer could be increased from its curren max value.

**Comment by santilland** [comment]
Single axis interaction has been implemented, as well as zoom limits removed. It is currently available in staging and will be part of the service release v1.1.
I will close the ticket now, if the functionality is not as expected or there are comments on it please write here.
