### ISSUE TITLE
Log in Login

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#91]
See my comment on #17 
> I realize this has been closed, but when testing I find that login and logout are a bit stiff, and suggest to replace them with log in and log out. login is a noun, but what one wants the user to do is an action, a verb; to "log in" (A login is when a user logs in), which for login would perhaps be to "perform (a) login", which I am sure you agree sounds a bit stiff/unnecessarlily long. See eg this [link](http://www.grammarunderground.com/login-vs-log-in-and-other-one-word-or-two-dilemmas.html).

**Comment by santilland** [comment]
Renamed login to tog in and logout to log out in commit https://github.com/ESA-VirES/VirES-Server/commit/6709ffa053eb1f01ce713dbd0576608a7c33c66d
There are two instances where i thought the noun actually made sense and i did not change it:
* "The User can either opt for a login natively with the VirES Service or ..."
* "Social Network Login Failure"
If it is considered these should be also changed please let me know and i will change them.
Let me know if this is considered as solved to close the ticket.

**Comment by miktoki** [comment]
I agree, using the noun correctly is fine.
