### ISSUE TITLE
Default time zone to UTC

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#93]
One of the early requirements was to be able to configure between timezones- eg. switch from UTC to local time.

Since it currently is not configurable, the default should be set to UTC as is done in the swarm data. (When I currently select a point in the analytics viewer the timestamp is in CEST)

**Comment by santilland** [comment]
Updated analytics viewer and timeslider to work and display UTC times in commit ff66d12b35bc4e0359abd025dffb31d92961c0a3. 
The timestamp when selecting a point is displayed in [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601) where a  Z i added directly after the time without a space. Z is the zone designator for the zero UTC offset.
Closing the ticket, if there is still any comments or feedback as always feel free to comment.
