### ISSUE TITLE
Navigation instructions in globe view

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#99]
Navigation instructions work fine in split scren view, but if one tries to view them in the globe view, no window/instructions appears. Furthermore, it looks like the problem propagates back to the splitscreen view.

**Comment by santilland** [comment]
There was an issues where the event handlers stopped listening to the event, this should be solved in commit 75d52ebd1a702c71e91e2b8c96359d0876de1cdd (available in staging not jet in production). Will close this ticket once deployed in production. As always any comments and feedback are welcome

**Comment by santilland** [comment]
Deployment to production was done already, will close this ticket. If any issues still persist please comment.
